import type { AnotacionApi, ConciliacionApi, ConsultaPublicaApi, DashboardApi, ExcepcionApi, HorarioApi, MonitorApi, SesionApi } from "./contratosMonitores";

export const monitoresDemo: MonitorApi[] = [
  {id:"mon-01",codigo_estudiante:"20211001001",full_name:"Kaleth Molina",department:"informatics_labs",is_active:true},
  {id:"mon-02",codigo_estudiante:"20211001002",full_name:"Sandra Ramírez",department:"informatics_labs",is_active:true},
  {id:"mon-03",codigo_estudiante:"20202002003",full_name:"Iván Prado",department:"electrical",is_active:true},
  {id:"mon-04",codigo_estudiante:"20212003004",full_name:"Laura Méndez",department:"electrical",is_active:true},
  {id:"mon-05",codigo_estudiante:"20221004005",full_name:"Daniela Ruiz",department:"physics",is_active:true},
  {id:"mon-06",codigo_estudiante:"20211005006",full_name:"Mateo Vargas",department:"physics",is_active:true},
];
export const horariosDemo: HorarioApi[] = monitoresDemo.flatMap((m,i)=>[{id:`hor-${i}-1`,monitor:m.id,monitor_name:m.full_name,weekday:i%2,start_time:"08:00:00",end_time:"12:00:00",is_active:true},{id:`hor-${i}-2`,monitor:m.id,monitor_name:m.full_name,weekday:(i%2)+2,start_time:"14:00:00",end_time:"18:00:00",is_active:true}]);
export const sesionesDemo: SesionApi[] = monitoresDemo.flatMap((m,mi)=>Array.from({length:4},(_,i)=>({id:`ses-${mi}-${i}`,monitor:m.id,monitor_name:m.full_name,work_day:`2026-08-${String(24-i).padStart(2,"0")}`,actual_start:"08:00:00",actual_end:i===0?"14:30:00":"14:00:00",normal_minutes:360,overtime_minutes:i===0?30:0,penalty_minutes:0,late_minutes:i===1?12:0,lateness_excused:i===2,lateness_exception_name:i===2?"Semana institucional":"",overtime_status:i===0?"pending":"not_applicable",overtime_review_note:""} as SesionApi)));
export const dashboardDemo: DashboardApi = {monitor_rows:monitoresDemo.map((m,i)=>({monitor_id:m.id,monitor_name:m.full_name,codigo_estudiante:m.codigo_estudiante,normal_minutes:((118+i*5)*60),approved_overtime_minutes:(i%3===0?8:4)*60,pending_overtime_minutes:(i%2===0?3.5:0)*60,annotation_delta_minutes:(i%4===0?-2:0)*60,penalty_minutes:0,remaining_minutes:0,late_count:i%3,has_memorandum:false})),pending_overtime:monitoresDemo.filter((_,i)=>i%2===0).map((m,i)=>({session_id:`ses-${i}-0`,monitor_name:m.full_name,work_day:"2026-08-24",overtime_minutes:30})),recent_annotations:[],notifications:[{id:"not-1",title:"Modo demo activo",body:"Los datos mostrados son simulados localmente.",is_read:false}]};
export const excepcionesDemo: ExcepcionApi[] = [{id:"exc-1",name:"Semana institucional",description:"Periodo sin retrasos.",start_date:"2026-08-24",end_date:"2026-08-28",department:null,department_label:"Todas las dependencias",ignore_lateness:true,approve_overtime:false,is_active:true}];
export const anotacionesDemo: AnotacionApi[] = [{id:"ano-1",leader:"demo",monitor:"mon-01",session:null,department:"informatics_labs",annotation_type:"virtual_hours",description:"Apoyo remoto",action:"add",delta_minutes:120,occurred_on:"2026-08-24",created_at:"2026-08-24T10:00:00Z"}];
export const conciliacionesDemo: ConciliacionApi[] = [{id:"raw-1",import_job:"demo",row_number:2,raw_full_name:"S. RAMIREZ",raw_department:"informatics_labs",work_day:"2026-08-24",entry_at:null,exit_at:null,monitor:null,monitor_name:"",reconciliation_status:"pending",manual_review_reason:"Coincidencia ambigua",processed_at:null,processing_error:""}];
export function consultaDemo(codigo:string): ConsultaPublicaApi | null { const m=monitoresDemo.find((item)=>item.codigo_estudiante===codigo);if(!m)return null;const sesiones=sesionesDemo.filter((item)=>item.monitor===m.id).slice(0,4);return {monitor:m,metrics:{normal_minutes:118*60,approved_overtime_minutes:8*60,pending_overtime_minutes:30,annotation_delta_minutes:0,total_minutes:126*60,remaining_minutes:66*60,late_count:1,has_memorandum:false},recent_sessions:sesiones}; }
