import { obtenerSesion } from "@/features/auth/lib/sesion";
import { solicitarAulas } from "@/features/monitores/api/clienteMonitores";
import type { FreePractice, PracticeStudent } from "@/features/practicas-libres/types";
type ApiPractice = { id: string; estado: FreePractice["status"]; inicio: string; finEstimada: string; finReal: string | null; aulaId: string; responsableTipo: FreePractice["responsibleType"]; softwareSolicitado: string | null; aula: { codigo: string }; estudiante: { id: string; codigo: string; nombre: string; correo: string | null } | null; docente?: { id: string; documento: string | null; nombre: string; correo: string | null } | null };
const auth = () => { const token = obtenerSesion()?.tokenAcceso; if (!token) throw new Error("La sesión expiró. Inicie sesión nuevamente."); return token; };
const map = (p: ApiPractice): FreePractice => { const requesterType = p.estudiante ? "ESTUDIANTE" : "DOCENTE"; const responsable = p.estudiante ? { id: p.estudiante.id, code: p.estudiante.codigo, name: p.estudiante.nombre, email: p.estudiante.correo ?? undefined } : { id: p.docente?.id ?? "", code: p.docente?.documento ?? "Sin documento", name: p.docente?.nombre ?? "Docente responsable", email: p.docente?.correo ?? undefined }; return { id: p.id, requesterType, status: p.estado, roomId: p.aulaId, roomCode: p.aula.codigo, start: p.inicio, estimatedEnd: p.finEstimada, actualEnd: p.finReal ?? undefined, responsibleType: p.responsableTipo, requestedSoftware: p.softwareSolicitado ?? "Sin especificar", student: { ...responsable, activeFine: false } }; };
export const listarPracticas = async () => (await solicitarAulas<ApiPractice[]>("/practicas-libres", auth())).map(map);
export const crearPractica = async (input: { codigoEstudiante: string; nombreEstudiante: string; correoEstudiante?: string; aulaId: string; softwareId?: string; softwareSolicitado: string; responsableTipo: FreePractice["responsibleType"]; inicio: string; finEstimada: string; responsables?: Array<{ tipo: "ESTUDIANTE" | "DOCENTE"; documento: string; nombre: string; correo?: string }> }) => { const response = await solicitarAulas<ApiPractice[]>("/practicas-libres", auth(), { method: "POST", body: JSON.stringify(input) }); return map(response[0]); };
export const finalizarPractica = async (id: string, cumplioReglas: boolean, observacionesIncumplimiento?: string) => map(await solicitarAulas<ApiPractice>(`/practicas-libres/${id}/finalizar`, auth(), { method: "PATCH", body: JSON.stringify({ cumplioReglas, observacionesIncumplimiento }) }));
export const cancelarPractica = async (id: string) => map(await solicitarAulas<ApiPractice>(`/practicas-libres/${id}/cancelar`, auth(), { method: "PATCH", body: JSON.stringify({}) }));
export async function buscarEstudiantePractica(codigo: string) {
  try { const item = await solicitarAulas<{ id: string; codigo: string; nombre: string; correo: string | null; multas: unknown[]; practicas: unknown[] }>(`/practicas-libres/estudiantes/${encodeURIComponent(codigo)}`, auth()); return { id: item.id, code: item.codigo, name: item.nombre, email: item.correo ?? undefined, activeFine: item.multas.length > 0, activePractice: item.practicas.length > 0 }; }
  catch (error) { if (typeof error === "object" && error && "estado" in error && (error as { estado: number }).estado === 404) return null; throw error; }
}
export async function buscarDocentePractica(documento: string) {
  try { const item = await solicitarAulas<{ id: string; documento: string | null; nombre: string; correo: string | null; practicasLibres: unknown[] }>(`/practicas-libres/docentes/${encodeURIComponent(documento)}`, auth()); return { id: item.id, code: item.documento ?? documento, name: item.nombre, email: item.correo ?? undefined, activePractice: item.practicasLibres.length > 0 }; }
  catch (error) { if (typeof error === "object" && error && "estado" in error && (error as { estado: number }).estado === 404) return null; throw error; }
}
export async function crearEstudianteDesdePractica(input: { codigo: string; nombre: string; correo?: string }) {
  const item = await solicitarAulas<{ id: string; codigo: string; nombre: string; correo: string | null }>("/practicas-libres/estudiantes", auth(), { method: "POST", body: JSON.stringify(input) });
  return { id: item.id, code: item.codigo, name: item.nombre, email: item.correo ?? undefined, activeFine: false } satisfies PracticeStudent;
}
