"use client";

import { useEffect, useMemo, useState } from "react";
import { listarAulas } from "@/features/aulas/api/aulasApi";
import { buscarEstudiantePractica, cancelarPractica, crearPractica, finalizarPractica, listarPracticas } from "@/features/practicas-libres/api/practicasApi";
import type { Room } from "@/features/aulas/types";
import type { FreePractice, PracticeStudent } from "@/features/practicas-libres/types";
import styles from "./FreePracticesView.module.css";

export function FreePracticesView() {
  const [practices, setPractices] = useState<FreePractice[]>([]); const [rooms, setRooms] = useState<Room[]>([]); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [query, setQuery] = useState("");
  const reload = async () => { try { const [nextPractices, nextRooms] = await Promise.all([listarPracticas(), listarAulas()]); setPractices(nextPractices); setRooms(nextRooms); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible cargar prácticas."); } };
  useEffect(() => { void reload(); }, []);
  const visible = useMemo(() => practices.filter((item) => `${item.student.name} ${item.student.code} ${item.roomCode}`.toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))), [practices, query]);
  const finish = async (item: FreePractice) => { try { await finalizarPractica(item.id); await reload(); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible finalizar."); } };
  const cancel = async (item: FreePractice) => { try { await cancelarPractica(item.id); await reload(); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible cancelar."); } };
  return <><section className={`page-heading ${styles.heading}`}><div><h1>Prácticas Libres</h1><p>Registro validado por disponibilidad y restricciones del backend.</p></div><button type="button" className="button-primary" onClick={() => setShowForm(true)}>+ Nueva práctica libre</button></section>{notice && <div className={styles.notice}>{notice}</div>}<section className={styles.contentCard}><div className={styles.toolbar}><label className={styles.search}><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar estudiante o aula" /></label></div><div className="table-wrap"><table className={styles.practiceTable}><thead><tr><th>Estudiante</th><th>Aula</th><th>Inicio</th><th>Fin estimado</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.student.name}</strong><small>{item.student.code}</small></td><td>{item.roomCode}</td><td>{format(item.start)}</td><td>{format(item.estimatedEnd)}</td><td>{item.status}</td><td>{(item.status === "ACTIVO" || item.status === "VENCIDO") && <><button type="button" onClick={() => void finish(item)}>Finalizar</button>{item.status === "ACTIVO" && <button type="button" onClick={() => void cancel(item)}>Cancelar</button>}</>}</td></tr>)}{!visible.length && <tr><td colSpan={6} className={styles.emptyTable}>No hay prácticas registradas.</td></tr>}</tbody></table></div></section>{showForm && <PracticeForm rooms={rooms} onClose={() => setShowForm(false)} onSave={async (input) => { try { await crearPractica(input); await reload(); setShowForm(false); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible registrar la práctica."); } }} />}</>;
}

function PracticeForm({ rooms, onClose, onSave }: { rooms: Room[]; onClose: () => void; onSave: (input: { codigoEstudiante: string; nombreEstudiante: string; correoEstudiante?: string; aulaId: string; inicio: string; finEstimada: string }) => Promise<void> }) {
  const [codigo, setCodigo] = useState(""); const [student, setStudent] = useState<PracticeStudent | null>(null); const [nombre, setNombre] = useState(""); const [correo, setCorreo] = useState(""); const [aulaId, setAulaId] = useState(""); const [fecha, setFecha] = useState(new Intl.DateTimeFormat("en-CA", { timeZone: "America/Bogota" }).format(new Date())); const [hora, setHora] = useState("08:00");
  const lookup = async () => { const found = await buscarEstudiantePractica(codigo); setStudent(found); if (found) { setNombre(found.name); setCorreo(found.email ?? ""); } };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const end = `${String(Number(hora.slice(0, 2)) + 2).padStart(2, "0")}:00`; void onSave({ codigoEstudiante: codigo, nombreEstudiante: nombre, correoEstudiante: correo || undefined, aulaId, inicio: `${fecha}T${hora}:00-05:00`, finEstimada: `${fecha}T${end}:00-05:00` }); };
  return <div className={styles.backdrop}><section className={styles.dialog}><header><h2>Nueva práctica libre</h2><button type="button" onClick={onClose}>×</button></header><form onSubmit={submit}><label>Código estudiantil<input value={codigo} onChange={(event) => setCodigo(event.target.value)} required /></label><button type="button" onClick={() => void lookup()}>Buscar estudiante</button>{student?.activeFine && <p className={styles.inlineError}>El estudiante tiene una multa activa.</p>}<label>Nombre<input value={nombre} onChange={(event) => setNombre(event.target.value)} required /></label><label>Correo<input type="email" value={correo} onChange={(event) => setCorreo(event.target.value)} /></label><label>Aula<select value={aulaId} onChange={(event) => setAulaId(event.target.value)} required><option value="">Seleccione</option>{rooms.filter((room) => room.status === "disponible").map((room) => <option key={room.id} value={room.id}>Aula {room.code}</option>)}</select></label><label>Fecha<input type="date" value={fecha} onChange={(event) => setFecha(event.target.value)} required /></label><label>Hora<select value={hora} onChange={(event) => setHora(event.target.value)}>{["06:00", "08:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00"].map((value) => <option key={value}>{value}</option>)}</select></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className="button-primary" type="submit" disabled={!aulaId || !nombre || Boolean(student?.activeFine)}>Registrar</button></footer></form></section></div>;
}
function format(value: string) { return new Intl.DateTimeFormat("es-CO", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
