import { obtenerSesion } from "@/features/auth/lib/sesion";
import { descargarAulas, solicitarAulas } from "@/features/monitores/api/clienteMonitores";
import type { AudiovisualEquipment, AudiovisualLoan, AudiovisualResponsible } from "@/features/audiovisuales/types";

type ApiEquipment = { id: string; codigoInventario: string; nombre: string; tipo: string; marca: string | null; modelo: string | null; estado: AudiovisualEquipment["status"]; observacion: string | null; cantidadPrestamos?: number; minutosUsoAcumulado?: number; disponibleDesde?: string | null };
type ApiLoan = { id: string; estado: AudiovisualLoan["status"]; salidaEn: string; devolucionEstimada: string; devolucionReal: string | null; responsableTipo: AudiovisualLoan["responsibleType"]; docenteNombre: string; docenteDocumento: string; salonTexto: string; elementosAdicionales: string[] | null; observacionesPrestamo: string | null; recibidoPorTipo: AudiovisualLoan["receivedByType"] | null; observacionesDevolucion: string | null; devolucionCompleta: boolean | null; entregadoPor: { id: string; nombreCompleto: string } | null; recibidoPor: { id: string; nombreCompleto: string } | null; detalles: Array<{ equipoId: string }> };
type ApiResponsible = { id: string; nombreCompleto: string; nombreUsuario: string; cargo: string | null };
const token = () => { const value = obtenerSesion()?.tokenAcceso; if (!value) throw new Error("La sesión expiró. Inicie sesión nuevamente."); return value; };
const equipment = (value: ApiEquipment): AudiovisualEquipment => ({ id: value.id, inventoryCode: value.codigoInventario, name: value.nombre, type: value.tipo, brand: value.marca ?? undefined, model: value.modelo ?? undefined, status: value.estado, observation: value.observacion ?? undefined, usageHours: Math.round(((value.minutosUsoAcumulado ?? 0) / 60) * 10) / 10, loanCount: value.cantidadPrestamos ?? 0, availableFrom: value.disponibleDesde ?? undefined });
const loan = (value: ApiLoan): AudiovisualLoan => ({ id: value.id, status: value.estado, teacher: value.docenteNombre, teacherDocument: value.docenteDocumento, room: value.salonTexto, checkoutAt: value.salidaEn, dueAt: value.devolucionEstimada, returnedAt: value.devolucionReal ?? undefined, deliveredBy: value.entregadoPor?.nombreCompleto ?? "Sistema", deliveredById: value.entregadoPor?.id, responsibleType: value.responsableTipo, receivedBy: value.recibidoPor?.nombreCompleto, receivedById: value.recibidoPor?.id, receivedByType: value.recibidoPorTipo ?? undefined, returnObservations: value.observacionesDevolucion ?? undefined, loanObservations: value.observacionesPrestamo ?? undefined, returnedAll: value.devolucionCompleta ?? undefined, extras: value.elementosAdicionales ?? [], equipmentIds: value.detalles.map((detail) => detail.equipoId) });
export async function cargarAudiovisuales() { const [items, loans] = await Promise.all([solicitarAulas<{ datos: ApiEquipment[] }>("/prestamos-audiovisuales/equipos?limite=2000", token()), solicitarAulas<ApiLoan[]>("/prestamos-audiovisuales", token())]); return { equipment: items.datos.map(equipment), loans: loans.map(loan) }; }
export const listarResponsablesAudiovisuales = async () => (await solicitarAulas<ApiResponsible[]>("/prestamos-audiovisuales/responsables", token())).filter((item) => item.nombreUsuario.toLocaleLowerCase() !== "admin" && item.cargo?.toLocaleUpperCase() !== "ADMINISTRADOR").map((item): AudiovisualResponsible => ({ id: item.id, name: item.nombreCompleto, username: item.nombreUsuario, role: item.cargo ?? undefined }));
export const crearPrestamoAudiovisual = (input: { responsableTipo?: "MONITOR" | "TECNICO" | "ASISTENCIAL"; entregadoPorId: string; docenteId?: string; docenteNombre: string; docenteDocumento: string; salonTexto: string; elementosAdicionales: string[]; observaciones?: string; devolucionEstimada: string; equipos: Array<{ equipoId: string }> }) => solicitarAulas<ApiLoan>("/prestamos-audiovisuales", token(), { method: "POST", body: JSON.stringify(input) });
export const devolverPrestamoAudiovisual = (id: string, input: { recibidoPorId: string; devolucionCompleta: boolean; observaciones: string; equipos: Array<{ equipoId: string; estadoFisicoDevolucion: string; estadoFuncionalDevolucion: string }> }) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/devolver`, token(), { method: "PATCH", body: JSON.stringify({ ...input, devolucionReal: new Date().toISOString() }) });
export const cancelarPrestamoAudiovisual = (id: string) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/cancelar`, token(), { method: "PATCH", body: JSON.stringify({ motivo: "Cancelado desde operación" }) });
export const descargarFichasPrestamosAudiovisualesMes = (mes: string) => descargarAulas(`/reportes/prestamos-audiovisuales/pdf/mes?mes=${encodeURIComponent(mes)}`, token());
export const crearEquipoAudiovisual = (input: { codigoInventario: string; nombre: string; tipo: string; marca?: string; modelo?: string; estado: AudiovisualEquipment["status"]; observacion?: string }) => solicitarAulas<ApiEquipment>("/prestamos-audiovisuales/equipos", token(), { method: "POST", body: JSON.stringify(input) });
export const actualizarEquipoAudiovisual = (id: string, input: { codigoInventario?: string; nombre?: string; tipo?: string; marca?: string; modelo?: string; estado?: AudiovisualEquipment["status"]; observacion?: string }) => solicitarAulas<ApiEquipment>(`/prestamos-audiovisuales/equipos/${id}`, token(), { method: "PATCH", body: JSON.stringify(input) });
export const eliminarEquipoAudiovisual = (id: string) => solicitarAulas<ApiEquipment>(`/prestamos-audiovisuales/equipos/${id}`, token(), { method: "DELETE" });
export const importarVideobeamsExcel = (archivo: File) => { const data = new FormData(); data.append("archivo", archivo); return solicitarAulas<{ creados: number; archivo: string }>("/prestamos-audiovisuales/equipos/importar-excel", token(), { method: "POST", body: data }); };
