import { obtenerSesion } from "@/features/auth/lib/sesion";
import { solicitarAulas } from "@/features/monitores/api/clienteMonitores";
import type { AudiovisualEquipment, AudiovisualLoan } from "@/features/audiovisuales/types";

type ApiEquipment = { id: string; codigoInventario: string; nombre: string; tipo: string; estado: AudiovisualEquipment["status"]; observacion: string | null };
type ApiLoan = { id: string; estado: AudiovisualLoan["status"]; salidaEn: string; devolucionEstimada: string; devolucionReal: string | null; docente: { nombre: string }; aula: { codigo: string }; entregadoPor: { nombreCompleto: string } | null; detalles: Array<{ equipoId: string }> };
const token = () => { const value = obtenerSesion()?.tokenAcceso; if (!value) throw new Error("La sesión expiró. Inicie sesión nuevamente."); return value; };
const equipment = (value: ApiEquipment): AudiovisualEquipment => ({ id: value.id, inventoryCode: value.codigoInventario, name: value.nombre, type: value.tipo, status: value.estado, observation: value.observacion ?? undefined, usageHours: 0, loanCount: 0 });
const loan = (value: ApiLoan): AudiovisualLoan => ({ id: value.id, status: value.estado, teacher: value.docente.nombre, room: value.aula.codigo, checkoutAt: value.salidaEn, dueAt: value.devolucionEstimada, returnedAt: value.devolucionReal ?? undefined, deliveredBy: value.entregadoPor?.nombreCompleto ?? "Sistema", equipmentIds: value.detalles.map((detail) => detail.equipoId) });
export async function cargarAudiovisuales() { const [items, loans] = await Promise.all([solicitarAulas<{ datos: ApiEquipment[] }>("/prestamos-audiovisuales/equipos?limite=100", token()), solicitarAulas<ApiLoan[]>("/prestamos-audiovisuales", token())]); const counts = new Map<string, number>(); loans.forEach((item) => item.detalles.forEach((detail) => counts.set(detail.equipoId, (counts.get(detail.equipoId) ?? 0) + 1))); return { equipment: items.datos.map((item) => ({ ...equipment(item), loanCount: counts.get(item.id) ?? 0 })), loans: loans.map(loan) }; }
export const crearPrestamoAudiovisual = (input: { docenteId: string; aulaId: string; salidaEn: string; devolucionEstimada: string; equipos: Array<{ equipoId: string }> }) => solicitarAulas<ApiLoan>("/prestamos-audiovisuales", token(), { method: "POST", body: JSON.stringify(input) });
export const devolverPrestamoAudiovisual = (id: string, equipos: Array<{ equipoId: string; estadoFisicoDevolucion: string; estadoFuncionalDevolucion: string }>) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/devolver`, token(), { method: "PATCH", body: JSON.stringify({ devolucionReal: new Date().toISOString(), equipos }) });
export const cancelarPrestamoAudiovisual = (id: string) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/cancelar`, token(), { method: "PATCH", body: JSON.stringify({ motivo: "Cancelado desde operación" }) });
