import { obtenerSesion } from "@/features/auth/lib/sesion";
import { solicitarAulas } from "@/features/monitores/api/clienteMonitores";
import type { AudiovisualEquipment, AudiovisualLoan } from "@/features/audiovisuales/types";

type ApiEquipment = { id: string; codigoInventario: string; nombre: string; tipo: string; estado: AudiovisualEquipment["status"]; observacion: string | null };
type ApiLoan = { id: string; estado: AudiovisualLoan["status"]; salidaEn: string; devolucionEstimada: string; devolucionReal: string | null; responsableTipo: AudiovisualLoan["responsibleType"]; docenteNombre: string; docenteDocumento: string; salonTexto: string; elementosAdicionales: string[] | null; recibidoPorTipo: AudiovisualLoan["receivedByType"] | null; observacionesDevolucion: string | null; entregadoPor: { nombreCompleto: string } | null; detalles: Array<{ equipoId: string }> };
const token = () => { const value = obtenerSesion()?.tokenAcceso; if (!value) throw new Error("La sesión expiró. Inicie sesión nuevamente."); return value; };
const equipment = (value: ApiEquipment): AudiovisualEquipment => ({ id: value.id, inventoryCode: value.codigoInventario, name: value.nombre, type: value.tipo, status: value.estado, observation: value.observacion ?? undefined, usageHours: 0, loanCount: 0 });
const loan = (value: ApiLoan): AudiovisualLoan => ({ id: value.id, status: value.estado, teacher: value.docenteNombre, teacherDocument: value.docenteDocumento, room: value.salonTexto, checkoutAt: value.salidaEn, dueAt: value.devolucionEstimada, returnedAt: value.devolucionReal ?? undefined, deliveredBy: value.entregadoPor?.nombreCompleto ?? "Sistema", responsibleType: value.responsableTipo, receivedByType: value.recibidoPorTipo ?? undefined, returnObservations: value.observacionesDevolucion ?? undefined, extras: value.elementosAdicionales ?? [], equipmentIds: value.detalles.map((detail) => detail.equipoId) });
export async function cargarAudiovisuales() { const [items, loans] = await Promise.all([solicitarAulas<{ datos: ApiEquipment[] }>("/prestamos-audiovisuales/equipos?limite=100", token()), solicitarAulas<ApiLoan[]>("/prestamos-audiovisuales", token())]); const counts = new Map<string, number>(); loans.forEach((item) => item.detalles.forEach((detail) => counts.set(detail.equipoId, (counts.get(detail.equipoId) ?? 0) + 1))); return { equipment: items.datos.map((item) => ({ ...equipment(item), loanCount: counts.get(item.id) ?? 0 })), loans: loans.map(loan) }; }
export const crearPrestamoAudiovisual = (input: { responsableTipo: "MONITOR" | "TECNICO" | "ASISTENCIAL"; docenteNombre: string; docenteDocumento: string; salonTexto: string; elementosAdicionales: string[]; devolucionEstimada: string; equipos: Array<{ equipoId: string }> }) => solicitarAulas<ApiLoan>("/prestamos-audiovisuales", token(), { method: "POST", body: JSON.stringify(input) });
export const devolverPrestamoAudiovisual = (id: string, recibidoPorTipo: "MONITOR" | "TECNICO" | "ASISTENCIAL", observaciones: string, equipos: Array<{ equipoId: string; estadoFisicoDevolucion: string; estadoFuncionalDevolucion: string }>) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/devolver`, token(), { method: "PATCH", body: JSON.stringify({ devolucionReal: new Date().toISOString(), recibidoPorTipo, observaciones, equipos }) });
export const cancelarPrestamoAudiovisual = (id: string) => solicitarAulas<ApiLoan>(`/prestamos-audiovisuales/${id}/cancelar`, token(), { method: "PATCH", body: JSON.stringify({ motivo: "Cancelado desde operación" }) });
export const crearEquipoAudiovisual = (input: { codigoInventario: string; nombre: string; tipo: string; estado: AudiovisualEquipment["status"]; observacion?: string }) => solicitarAulas<ApiEquipment>("/prestamos-audiovisuales/equipos", token(), { method: "POST", body: JSON.stringify(input) });
export const actualizarEquipoAudiovisual = (id: string, input: { codigoInventario?: string; nombre?: string; tipo?: string; observacion?: string }) => solicitarAulas<ApiEquipment>(`/prestamos-audiovisuales/equipos/${id}`, token(), { method: "PATCH", body: JSON.stringify(input) });
export const eliminarEquipoAudiovisual = (id: string) => solicitarAulas<ApiEquipment>(`/prestamos-audiovisuales/equipos/${id}`, token(), { method: "DELETE" });
