"use client";

import { useEffect, useMemo, useState } from "react";
import { cambiarEstadoCredencial, crearCredencial, listarCredenciales, type CredencialApi } from "@/features/credenciales/api/credencialesApi";
import styles from "./CredentialsView.module.css";

export function CredentialsView() {
  const [items, setItems] = useState<CredencialApi[]>([]);
  const [query, setQuery] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const reload = async () => { try { setItems(await listarCredenciales()); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible cargar las credenciales."); } };
  useEffect(() => { void reload(); }, []);
  const visible = useMemo(() => items.filter((item) => `${item.nombre} ${item.categoria} ${item.usuario ?? ""}`.toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))), [items, query]);
  const toggle = async (item: CredencialApi) => { try { await cambiarEstadoCredencial(item.id, item.estado === "ACTIVA" ? "INACTIVA" : "ACTIVA"); await reload(); setNotice("Estado actualizado."); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible cambiar el estado."); } };
  return <><section className={`page-heading ${styles.heading}`}><div><h1>Credenciales Operativas</h1><p>Los secretos permanecen cifrados y nunca se muestran en esta pantalla.</p></div><button type="button" className="button-primary" onClick={() => setShowForm(true)}>+ Nueva credencial</button></section>{notice && <div className={styles.notice}>{notice}</div>}<section className={styles.contentCard}><div className={styles.toolbar}><label className={styles.search}><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nombre, categoría o usuario" /></label><span className={styles.resultCount}>{visible.length} resultado(s)</span></div><div className="table-wrap"><table className={styles.credentialsTable}><thead><tr><th>Credencial</th><th>Categoría</th><th>Usuario</th><th>Accesos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.nombre}</strong><small>{item.descripcion ?? "Sin descripción"}</small></td><td>{item.categoria}</td><td>{item.usuario ?? "—"}</td><td>{item.accesos.length}</td><td>{item.estado}</td><td><button type="button" onClick={() => void toggle(item)}>{item.estado === "ACTIVA" ? "Desactivar" : "Activar"}</button></td></tr>)}{!visible.length && <tr><td colSpan={6} className={styles.emptyTable}>No hay credenciales registradas.</td></tr>}</tbody></table></div></section>{showForm && <CredentialForm onClose={() => setShowForm(false)} onSave={async (data) => { try { await crearCredencial(data); await reload(); setShowForm(false); setNotice("Credencial creada correctamente."); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible crear la credencial."); } }} />}</>;
}

function CredentialForm({ onClose, onSave }: { onClose: () => void; onSave: (data: { nombre: string; categoria: string; usuario?: string; secreto: string; descripcion?: string }) => Promise<void> }) {
  const [nombre, setNombre] = useState(""); const [categoria, setCategoria] = useState(""); const [usuario, setUsuario] = useState(""); const [secreto, setSecreto] = useState(""); const [descripcion, setDescripcion] = useState("");
  return <div className={styles.backdrop}><section className={styles.dialog}><header><h2>Nueva credencial</h2><button type="button" onClick={onClose}>×</button></header><form onSubmit={(event) => { event.preventDefault(); void onSave({ nombre, categoria, usuario: usuario || undefined, secreto, descripcion: descripcion || undefined }); }}><label>Nombre<input value={nombre} onChange={(event) => setNombre(event.target.value)} required /></label><label>Categoría<input value={categoria} onChange={(event) => setCategoria(event.target.value)} required /></label><label>Usuario<input value={usuario} onChange={(event) => setUsuario(event.target.value)} /></label><label>Secreto<input type="password" value={secreto} onChange={(event) => setSecreto(event.target.value)} required autoComplete="new-password" /></label><label>Descripción<textarea value={descripcion} onChange={(event) => setDescripcion(event.target.value)} /></label><footer><button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="button-primary">Guardar</button></footer></form></section></div>;
}
