import { obtenerSesion } from "@/features/auth/lib/sesion";
import { solicitarAulas } from "@/features/monitores/api/clienteMonitores";
const token = () => { const value = obtenerSesion()?.tokenAcceso; if (!value) throw new Error("La sesión expiró. Inicie sesión nuevamente."); return value; };
export type CredencialApi = { id: string; nombre: string; usuario: string | null; descripcion: string | null; estado: "ACTIVA" | "INACTIVA"; creadoEn: string; actualizadoEn: string; accesos: Array<{ usuarioId: string; puedeVer: boolean; puedeEditar: boolean; usuario?: { id: string; nombreCompleto: string; nombreUsuario: string } }>; rolesAutorizados: Array<{ rolId: string; rol: { id: string; nombre: string } }> };
export type UsuarioApi = { id: string; nombreCompleto: string; nombreUsuario: string; correo: string; estado: string };
export type RolApi = { id: string; nombre: string };
export const listarCredenciales = () => solicitarAulas<CredencialApi[]>("/credenciales", token());
export const listarUsuariosParaCredenciales = () => solicitarAulas<UsuarioApi[]>("/usuarios", token());
export const listarRolesParaCredenciales = async () => (await solicitarAulas<Array<{ id: string; nombre: string }>>("/roles", token())).map(({ id, nombre }) => ({ id, nombre }));
export const crearCredencial = (data: { nombre: string; usuario?: string; secreto?: string; descripcion?: string; estado?: "ACTIVA" | "INACTIVA" }) => solicitarAulas<CredencialApi>("/credenciales", token(), { method: "POST", body: JSON.stringify(data) });
export const actualizarCredencial = (id: string, data: { nombre?: string; usuario?: string; descripcion?: string; estado?: "ACTIVA" | "INACTIVA" }) => solicitarAulas<CredencialApi>(`/credenciales/${id}`, token(), { method: "PATCH", body: JSON.stringify({ ...data, motivoCambio: "Actualizado desde Credenciales" }) });
export const actualizarAccesoCredencial = (id: string, usuarioId: string, puedeVer: boolean, puedeEditar: boolean) => solicitarAulas(`/credenciales/${id}/accesos`, token(), { method: "POST", body: JSON.stringify({ usuarioId, puedeVer, puedeEditar }) });
export const actualizarRolesCredencial = (id: string, rolIds: string[]) => solicitarAulas(`/credenciales/${id}/roles`, token(), { method: "PUT", body: JSON.stringify({ rolIds }) });
export const eliminarCredencial = (id: string, contrasenaUsuario: string) => solicitarAulas(`/credenciales/${id}`, token(), { method: "DELETE", body: JSON.stringify({ contrasenaUsuario }) });
export const cambiarContrasenaCredencial = (id: string, data: { contrasenaUsuario: string; secretoActual: string; secretoNuevo: string }) => solicitarAulas(`/credenciales/${id}/secreto`, token(), { method: "POST", body: JSON.stringify(data) });
export const verificarAccesoCredenciales = (contrasena: string) => solicitarAulas<{ desbloqueado: boolean; expiraEn: number }>("/credenciales/verificar-acceso", token(), { method: "POST", body: JSON.stringify({ contrasena }) });
export const consultarSecretoCredencial = (id: string) => solicitarAulas<{ id: string; secreto: string }>("/credenciales/" + id + "/secreto", token());
