export const navigation = [
  { href: "/gestion-aulas", label: "Dashboard" },
  { href: "/horarios", label: "Horarios" },
  { href: "/aulas", label: "Aulas" },
  { href: "/disponibilidad", label: "Disponibilidad" },
  { href: "/practicas-libres", label: "Prácticas Libres" },
  { href: "/prestamos-docentes", label: "Préstamos Docentes" },
  { href: "/audiovisuales", label: "Audiovisuales" },
  { href: "/software", label: "Software Instalado" },
  { href: "/observaciones", label: "Observaciones" },
  { href: "/limpieza", label: "Limpieza" },
  { href: "/tareas", label: "Tareas Operativas" },
  { href: "/multas", label: "Multas" },
  { href: "/credenciales", label: "Credenciales" },
] as const;
