"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "./UsuariosView.module.css";
import type { Usuario } from "../types";
import { actualizarUsuario, crearUsuario, listarUsuarios } from "@/features/usuarios/api/usuariosApi";

const inicial: Usuario[] = [];
const vacio = { nombreCompleto:"", nombreUsuario:"", correo:"", cargo:"", dependencia:"Aulas de Software", permisos:[] as string[], password:"" };

export function UsuariosView() {
  const [usuarios,setUsuarios]=useState<Usuario[]>(inicial); const [busqueda,setBusqueda]=useState(""); const [edicion,setEdicion]=useState<string|null>(null); const [form,setForm]=useState(vacio); const [aviso,setAviso]=useState("");
  const cargar=async()=>{try{setUsuarios(await listarUsuarios())}catch(error){setAviso(error instanceof Error?error.message:"No fue posible cargar usuarios.")}};
  useEffect(()=>{void cargar()},[]);
  const visibles=useMemo(()=>usuarios.filter(u=>`${u.nombreCompleto} ${u.nombreUsuario} ${u.correo}`.toLowerCase().includes(busqueda.toLowerCase())),[usuarios,busqueda]);
  const guardar=async(e:React.FormEvent)=>{e.preventDefault();if(!form.nombreCompleto||!form.nombreUsuario||!form.correo||(!edicion&&!form.password))return;try{const data={nombreCompleto:form.nombreCompleto,nombreUsuario:form.nombreUsuario,correo:form.correo,cargo:form.cargo||undefined};if(edicion)await actualizarUsuario(edicion,{...data,password:form.password||undefined});else await crearUsuario({...data,password:form.password});await cargar();setAviso(edicion?"Usuario actualizado correctamente.":"Usuario creado correctamente.");setForm(vacio);setEdicion(null)}catch(error){setAviso(error instanceof Error?error.message:"No fue posible guardar el usuario.")}};
  const editar=(u:Usuario)=>{setEdicion(u.id);setForm({nombreCompleto:u.nombreCompleto,nombreUsuario:u.nombreUsuario,correo:u.correo,cargo:u.cargo,dependencia:u.dependencia,permisos:u.permisos,password:""})};
  return <><section className="page-heading"><div><span className={styles.etiqueta}>Administración del sistema</span><h1>Usuarios</h1><p>Cree y modifique las cuentas de acceso del sistema.</p></div><span className="live-status">{usuarios.filter(u=>u.estado==="ACTIVA").length} activos</span></section>{aviso&&<div className={`${styles.aviso} ${styles.exito}`}>{aviso}</div>}<div className={styles.layout}><section className={styles.card}><header><h2>{edicion?"Modificar usuario":"Crear usuario"}</h2><p>Los roles y permisos se administran desde sus catálogos.</p></header><form onSubmit={(event)=>void guardar(event)}><label><span>Nombre completo</span><input value={form.nombreCompleto} onChange={e=>setForm({...form,nombreCompleto:e.target.value})} required /></label><label><span>Nombre de usuario</span><input value={form.nombreUsuario} onChange={e=>setForm({...form,nombreUsuario:e.target.value})} required /></label><label><span>Correo</span><input type="email" value={form.correo} onChange={e=>setForm({...form,correo:e.target.value})} required /></label><label><span>{edicion?"Nueva contraseña (opcional)":"Contraseña"}</span><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required={!edicion} minLength={10} /></label><label><span>Cargo</span><input value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})} /></label><footer><button type="button" className="button-secondary" onClick={()=>{setForm(vacio);setEdicion(null)}}>Limpiar</button><button className="button-primary">{edicion?"Guardar cambios":"Crear usuario"}</button></footer></form></section><section className={styles.card}><header><div><h2>Usuarios registrados</h2><p>Datos cargados desde la API central.</p></div><input className={styles.search} placeholder="Buscar usuario..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></header><div className={styles.list}>{visibles.map(u=><article key={u.id}><div><strong>{u.nombreCompleto}</strong><small>{u.nombreUsuario} · {u.correo}</small><small>{u.cargo||"Sin cargo"} · {u.dependencia}</small></div><div className={styles.meta}><span className={`${styles.status} ${u.estado==="ACTIVA"?styles.active:styles.inactive}`}>{u.estado}</span><span>{u.permisos.length} roles</span><button onClick={()=>editar(u)}>Modificar</button></div></article>)}{!visibles.length&&<p className={styles.empty}>No hay usuarios que coincidan con la búsqueda.</p>}</div></section></div></>;
}
