"use client";
import { useMemo, useState } from "react";
import styles from "./UsuariosView.module.css";
import type { Usuario } from "../types";

const permisos = ["Dashboard","Horarios","Aulas","Prácticas libres","Préstamos docentes","Audiovisuales","Software instalado","Multas","Observaciones","Limpieza","Tareas operativas","Gestión de monitores","Credenciales","Reportes","Administración del sistema"] as const;
const inicial: Usuario[] = [];
const vacio = { nombreCompleto:"", nombreUsuario:"", correo:"", cargo:"", dependencia:"Aulas de Software", permisos:[] as string[] };

export function UsuariosView() {
  const [usuarios,setUsuarios]=useState(inicial); const [busqueda,setBusqueda]=useState(""); const [edicion,setEdicion]=useState<string|null>(null); const [form,setForm]=useState(vacio); const [aviso,setAviso]=useState("");
  const visibles=useMemo(()=>usuarios.filter(u=>`${u.nombreCompleto} ${u.nombreUsuario} ${u.correo}`.toLowerCase().includes(busqueda.toLowerCase())),[usuarios,busqueda]);
  const guardar=(e:React.FormEvent)=>{e.preventDefault();if(!form.nombreCompleto||!form.nombreUsuario||!form.correo)return; if(edicion){setUsuarios(actual=>actual.map(u=>u.id===edicion?{...u,...form}:u));setAviso("Usuario actualizado correctamente.")}else{setUsuarios(actual=>[{...form,id:`usuario-${Date.now()}`,estado:"ACTIVA"},...actual]);setAviso("Usuario creado correctamente.")}setForm(vacio);setEdicion(null)};
  const editar=(u:Usuario)=>{setEdicion(u.id);setForm({nombreCompleto:u.nombreCompleto,nombreUsuario:u.nombreUsuario,correo:u.correo,cargo:u.cargo,dependencia:u.dependencia,permisos:u.permisos})};
  const alternarPermiso=(permiso:string)=>setForm(actual=>({...actual,permisos:actual.permisos.includes(permiso)?actual.permisos.filter(p=>p!==permiso):[...actual.permisos,permiso]}));
  return <><section className="page-heading"><div><span className={styles.etiqueta}>Administración del sistema</span><h1>Usuarios</h1><p>Cree, modifique y administre los permisos de acceso de los usuarios.</p></div><span className="live-status">{usuarios.filter(u=>u.estado==="ACTIVA").length} activos</span></section>{aviso&&<div className={`${styles.aviso} ${styles.exito}`}>{aviso}</div>}<div className={styles.layout}><section className={styles.card}><header><h2>{edicion?"Modificar usuario":"Crear usuario"}</h2><p>Los permisos se asignan individualmente según las funciones.</p></header><form onSubmit={guardar}><label><span>Nombre completo</span><input value={form.nombreCompleto} onChange={e=>setForm({...form,nombreCompleto:e.target.value})} required /></label><label><span>Nombre de usuario</span><input value={form.nombreUsuario} onChange={e=>setForm({...form,nombreUsuario:e.target.value})} required /></label><label><span>Correo</span><input type="email" value={form.correo} onChange={e=>setForm({...form,correo:e.target.value})} required /></label><div className={styles.two}><label><span>Cargo</span><input value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})} /></label><label><span>Dependencia</span><select value={form.dependencia} onChange={e=>setForm({...form,dependencia:e.target.value})}><option>Aulas de Software</option><option>Eléctrica y Electrónica</option><option>Física</option></select></label></div><fieldset><legend>Permisos de acceso</legend><div className={styles.permissionGrid}>{permisos.map(p=><label key={p}><input type="checkbox" checked={form.permisos.includes(p)} onChange={()=>alternarPermiso(p)}/><span>{p}</span></label>)}</div></fieldset><footer><button type="button" className="button-secondary" onClick={()=>{setForm(vacio);setEdicion(null)}}>Limpiar</button><button className="button-primary">{edicion?"Guardar cambios":"Crear usuario"}</button></footer></form></section><section className={styles.card}><header><div><h2>Usuarios registrados</h2><p>Consulte cuentas y ajuste sus permisos.</p></div><input className={styles.search} placeholder="Buscar usuario..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></header><div className={styles.list}>{visibles.map(u=><article key={u.id}><div><strong>{u.nombreCompleto}</strong><small>{u.nombreUsuario} · {u.correo}</small><small>{u.cargo||"Sin cargo"} · {u.dependencia}</small></div><div className={styles.meta}><span className={`${styles.status} ${u.estado==="ACTIVA"?styles.active:styles.inactive}`}>{u.estado}</span><span>{u.permisos.length} permisos</span><button onClick={()=>editar(u)}>Modificar</button></div></article>)}{!visibles.length&&<p className={styles.empty}>No hay usuarios que coincidan con la búsqueda.</p>}</div></section></div></>;
}
