"use client";
import { useMemo,useState } from "react";
import { conciliacionesIniciales,monitores } from "@/features/monitores/datos/datosMonitores";
import { usarPaginacion } from "@/features/monitores/ganchos/usarPaginacion";
import { Paginacion } from "./Paginacion";
import estilos from "./VistasMonitores.module.css";

export function ConciliacionAsistencia(){
 const [registros,setRegistros]=useState(conciliacionesIniciales);const [nombre,setNombre]=useState("");const [dependencia,setDependencia]=useState("");const [fecha,setFecha]=useState("");const [motivo,setMotivo]=useState("");const [selecciones,setSelecciones]=useState<Record<string,string>>({});const [aviso,setAviso]=useState("");
 const filtrados=useMemo(()=>registros.filter((item)=>(!nombre||item.nombreOriginal.toLocaleLowerCase("es").includes(nombre.toLocaleLowerCase("es")))&&(!dependencia||item.dependencia===dependencia)&&(!fecha||item.fecha===fecha)&&(!motivo||item.motivo.toLocaleLowerCase("es").includes(motivo.toLocaleLowerCase("es")))),[registros,nombre,dependencia,fecha,motivo]);const paginacion=usarPaginacion(filtrados,8);
 const limpiar=()=>{setNombre("");setDependencia("");setFecha("");setMotivo("");paginacion.reiniciar()};
 return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Asistencia</span><h1>Registros pendientes de conciliación</h1><p>Vincule nombres no reconocidos con el monitor correcto.</p></div><span className={`${estilos.insignia} ${estilos.advertencia}`}>{filtrados.length} visibles</span></section>{aviso&&<div className={`${estilos.aviso} ${estilos.avisoExito}`}>{aviso}</div>}<section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Nombre crudo</span><input value={nombre} onChange={(e)=>{setNombre(e.target.value);paginacion.reiniciar()}} placeholder="Filtrar nombre"/></label><label className={estilos.campo}><span>Dependencia</span><select value={dependencia} onChange={(e)=>{setDependencia(e.target.value);paginacion.reiniciar()}}><option value="">Todas</option>{[...new Set(registros.map((item)=>item.dependencia))].map((item)=><option key={item}>{item}</option>)}</select></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={fecha} onChange={(e)=>{setFecha(e.target.value);paginacion.reiniciar()}}/></label><label className={estilos.campo}><span>Motivo</span><input value={motivo} onChange={(e)=>{setMotivo(e.target.value);paginacion.reiniciar()}} placeholder="Filtrar motivo"/></label><button type="button" className={estilos.botonSecundario} onClick={limpiar}>Limpiar</button></div><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Nombre crudo</th><th>Dependencia</th><th>Fecha</th><th>Motivo</th><th>Asignar monitor</th></tr></thead><tbody>{paginacion.visibles.map((registro)=><tr key={registro.id}><td><strong>{registro.nombreOriginal}</strong></td><td>{registro.dependencia}</td><td>{registro.fecha}</td><td>{registro.motivo}</td><td><div className={estilos.accionesTabla}><select value={selecciones[registro.id]??""} onChange={(e)=>setSelecciones({...selecciones,[registro.id]:e.target.value})}><option value="">Seleccione</option>{monitores.filter((item)=>item.dependencia===registro.dependencia).map((item)=><option key={item.id} value={item.id}>{item.nombre}</option>)}</select><button type="button" disabled={!selecciones[registro.id]} onClick={()=>{const monitor=monitores.find((item)=>item.id===selecciones[registro.id]);setRegistros((actual)=>actual.filter((item)=>item.id!==registro.id));setAviso(`${registro.nombreOriginal} fue vinculado con ${monitor?.nombre}.`)}}>Vincular</button></div></td></tr>)}{filtrados.length===0&&<tr><td colSpan={5} className={estilos.vacio}>No hay registros pendientes.</td></tr>}</tbody></table></div><Paginacion {...paginacion} total={filtrados.length}/></section></>;
}
