"use client";
import { useMemo,useState } from "react";
import { adaptarMonitor, nombreDependencia } from "@/features/monitores/api/adaptadoresMonitores";
import type { ConciliacionApi, MonitorApi } from "@/features/monitores/api/contratosMonitores";
import { servicioMonitores } from "@/features/monitores/api/servicioMonitores";
import { usarRecursoApi } from "@/features/monitores/ganchos/usarRecursoApi";
import { usarPaginacion } from "@/features/monitores/ganchos/usarPaginacion";
import { Paginacion } from "./Paginacion";
import estilos from "./SistemaVisualMonitores.module.css";

export function ConciliacionAsistencia(){
 const recurso=usarRecursoApi(servicioMonitores.listarConciliaciones,[] as ConciliacionApi[]);const recursoMonitores=usarRecursoApi(servicioMonitores.listarMonitores,[] as MonitorApi[]);const [nombre,setNombre]=useState("");const [dependencia,setDependencia]=useState("");const [fecha,setFecha]=useState("");const [motivo,setMotivo]=useState("");const [selecciones,setSelecciones]=useState<Record<string,string>>({});const [aviso,setAviso]=useState("");const [procesando,setProcesando]=useState("");
 const monitores=useMemo(()=>recursoMonitores.datos.map(adaptarMonitor),[recursoMonitores.datos]);const filtrados=useMemo(()=>recurso.datos.filter((item)=>(!nombre||item.raw_full_name.toLocaleLowerCase("es").includes(nombre.toLocaleLowerCase("es")))&&(!dependencia||item.raw_department===dependencia)&&(!fecha||item.work_day===fecha)&&(!motivo||`${item.manual_review_reason} ${item.processing_error}`.toLocaleLowerCase("es").includes(motivo.toLocaleLowerCase("es")))),[recurso.datos,nombre,dependencia,fecha,motivo]);const paginacion=usarPaginacion(filtrados,8);
 const limpiar=()=>{setNombre("");setDependencia("");setFecha("");setMotivo("");paginacion.reiniciar()};
 const vincular=async(registro:ConciliacionApi)=>{const monitorId=selecciones[registro.id];if(!monitorId)return;setProcesando(registro.id);setAviso("");try{await servicioMonitores.asignarMonitor(registro.id,monitorId);recurso.setDatos((actual)=>actual.filter((item)=>item.id!==registro.id));setAviso(`${registro.raw_full_name} fue vinculado correctamente.`)}catch(problema){setAviso(problema instanceof Error?problema.message:"No fue posible vincular el registro.")}finally{setProcesando("")}};
 return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Asistencia</span><h1>Registros pendientes de conciliación</h1><p>Vincule nombres no reconocidos con el monitor correcto.</p></div><span className={`${estilos.insignia} ${estilos.advertencia}`}>{filtrados.length} visibles</span></section>{(recurso.error||recursoMonitores.error)&&<div className={`${estilos.aviso} ${estilos.avisoError}`}>{recurso.error||recursoMonitores.error}</div>}{aviso&&<div className={`${estilos.aviso} ${aviso.includes("correctamente")?estilos.avisoExito:estilos.avisoError}`}>{aviso}</div>}<section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Nombre crudo</span><input value={nombre} onChange={(e)=>{setNombre(e.target.value);paginacion.reiniciar()}} placeholder="Filtrar nombre"/></label><label className={estilos.campo}><span>Dependencia</span><select value={dependencia} onChange={(e)=>{setDependencia(e.target.value);paginacion.reiniciar()}}><option value="">Todas</option>{[...new Set(recurso.datos.map((item)=>item.raw_department))].map((item)=><option key={item}>{item}</option>)}</select></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={fecha} onChange={(e)=>{setFecha(e.target.value);paginacion.reiniciar()}}/></label><label className={estilos.campo}><span>Motivo</span><input value={motivo} onChange={(e)=>{setMotivo(e.target.value);paginacion.reiniciar()}} placeholder="Filtrar motivo"/></label><button type="button" className={estilos.botonSecundario} onClick={limpiar}>Limpiar</button></div><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Nombre crudo</th><th>Dependencia</th><th>Fecha</th><th>Motivo</th><th>Asignar monitor</th></tr></thead><tbody>{paginacion.visibles.map((registro)=><tr key={registro.id}><td><strong>{registro.raw_full_name}</strong></td><td>{nombreDependencia(registro.raw_department)}</td><td>{registro.work_day}</td><td>{registro.manual_review_reason||registro.processing_error||"Coincidencia no encontrada"}</td><td><div className={estilos.accionesTabla}><select value={selecciones[registro.id]??""} onChange={(e)=>setSelecciones({...selecciones,[registro.id]:e.target.value})}><option value="">Seleccione</option>{monitores.filter((item)=>recursoMonitores.datos.find((api)=>api.id===item.id)?.department===registro.raw_department).map((item)=><option key={item.id} value={item.id}>{item.nombre}</option>)}</select><button type="button" disabled={!selecciones[registro.id]||procesando===registro.id} onClick={()=>void vincular(registro)}>{procesando===registro.id?"Vinculando…":"Vincular"}</button></div></td></tr>)}{!recurso.cargando&&filtrados.length===0&&<tr><td colSpan={5} className={estilos.vacio}>No hay registros pendientes.</td></tr>}</tbody></table></div><Paginacion {...paginacion} total={filtrados.length}/></section></>;
}
