"use client";
import Link from "next/link";
import { useState,type FormEvent } from "react";
import { monitores,resumenesIniciales,sesionesIniciales } from "@/features/monitores/datos/datosMonitores";
import type { Monitor } from "@/features/monitores/tipos/modelosMonitores";
import { ResumenHoras } from "./ResumenHoras";
import { TablaSesiones } from "./TablaSesiones";
import estilos from "./VistasMonitores.module.css";

export function ConsultaPublica(){const[codigo,setCodigo]=useState("");const[monitor,setMonitor]=useState<Monitor|null>(null);const[error,setError]=useState("");const consultar=(e:FormEvent)=>{e.preventDefault();const encontrado=monitores.find((item)=>item.codigo===codigo.trim());setMonitor(encontrado??null);setError(encontrado?"":"No se encontró un monitor con el código indicado.")};return <div className={estilos.portadaPublica}><header className={estilos.marcaPublica}><div><strong>SGOAS · Gestión de Monitores</strong><span>Consulta institucional de horas</span></div><Link className={estilos.botonSecundario} href="/login?app=monitores">Ingresar al módulo</Link></header><main className={estilos.contenidoPublico}><section className={`${estilos.tarjeta} ${estilos.buscadorPublico}`}><header><div><span className={estilos.etiqueta}>Consulta pública</span><h2>Consulte sus horas de monitoría</h2><p>Ingrese el código estudiantil registrado en el sistema.</p></div></header><form className={estilos.formulario} onSubmit={consultar}><label className={estilos.campo}><span>Código estudiantil</span><input value={codigo} onChange={(e)=>{setCodigo(e.target.value);setError("")}} placeholder="Ej. 20211001001" required/></label><button className="button-primary" type="submit">Consultar</button><small style={{color:"var(--muted)"}}>Código de demostración: 20211001001</small></form>{error&&<div className={`${estilos.aviso} ${estilos.avisoError}`} role="alert">{error}</div>}</section>{monitor&&<section className={estilos.resultadoPublico}><section className={estilos.tarjeta}><div className={estilos.detalleMonitor}><div><h2>{monitor.nombre}</h2><p>Código {monitor.codigo} · {monitor.dependencia}</p></div><span className={`${estilos.insignia} ${estilos.exito}`}>Registro activo</span></div></section><ResumenHoras resumen={resumenesIniciales.find((item)=>item.monitorId===monitor.id)!} incluirAlertas/><TablaSesiones sesiones={sesionesIniciales.filter((item)=>item.monitorId===monitor.id)}/></section>}</main></div>}
