"use client";

import { useMemo, useState } from "react";
import { monitoresDemo } from "@/features/monitores/api/datosDemo";
import estilos from "./SistemaVisualMonitores.module.css";

type EstadoEnvio = "ENVIADO" | "PENDIENTE" | "SIN_CORREO";
type Memorando = { id: string; monitor: string; codigo: string; dependencia: string; retardos: number; correo: string; estado: EstadoEnvio; fechaEnvio?: string };

const inicial: Memorando[] = monitoresDemo.slice(0, 8).map((monitor, indice) => ({ id: `mem-${monitor.id}`, monitor: monitor.full_name, codigo: monitor.codigo_estudiante, dependencia: monitor.department === "physics" ? "Monitores Física" : monitor.department === "electrical" ? "Monitores Laboratorios" : "Monitores Aulas de Software", retardos: 3 + (indice % 3), correo: indice === 2 ? "" : `monitor${indice + 1}@udistrital.edu.co`, estado: indice === 2 ? "SIN_CORREO" : indice % 2 ? "PENDIENTE" : "ENVIADO", fechaEnvio: indice % 2 ? undefined : "2026-08-18 09:30" }));

export function GestionMemorandos() {
  const [memorandos, setMemorandos] = useState(inicial);
  const [texto, setTexto] = useState("");
  const [estado, setEstado] = useState("TODOS");
  const [dependencia, setDependencia] = useState("TODAS");
  const [aviso, setAviso] = useState("");
  const visibles = useMemo(() => memorandos.filter((item) => (!texto || `${item.monitor} ${item.codigo} ${item.correo}`.toLocaleLowerCase("es").includes(texto.toLocaleLowerCase("es"))) && (estado === "TODOS" || item.estado === estado) && (dependencia === "TODAS" || item.dependencia === dependencia)), [memorandos, texto, estado, dependencia]);
  const metricas = { total: memorandos.length, enviados: memorandos.filter((item) => item.estado === "ENVIADO").length, pendientes: memorandos.filter((item) => item.estado === "PENDIENTE").length, sinCorreo: memorandos.filter((item) => item.estado === "SIN_CORREO").length };
  const reenviar = (memorando: Memorando) => { if (!memorando.correo) { setAviso(`${memorando.monitor} no tiene correo registrado.`); return; } setMemorandos((actual) => actual.map((item) => item.id === memorando.id ? { ...item, estado: "ENVIADO", fechaEnvio: "2026-08-28 09:00" } : item)); setAviso(`Memorando reenviado a ${memorando.correo}.`); };
  return <div className={estilos.gestionMemorandos}><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Seguimiento disciplinario</span><h1>Memorandos</h1><p>Consulta memorandos generados por retardos, descarga el PDF y reenvíalos cuando el monitor tenga correo registrado.</p></div></section><section className={estilos.metricas}><Metrica etiqueta="Total" valor={metricas.total} tono="violeta"/><Metrica etiqueta="Enviados" valor={metricas.enviados} tono="verde"/><Metrica etiqueta="Pendientes" valor={metricas.pendientes} tono="ambar"/><Metrica etiqueta="Sin correo" valor={metricas.sinCorreo} tono="azul"/></section>{aviso && <div className={`${estilos.aviso} ${aviso.includes("no tiene") ? estilos.avisoError : estilos.avisoExito}`}>{aviso}</div>}<section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><Campo etiqueta="Buscar" ancho><input value={texto} onChange={(e) => setTexto(e.target.value)} placeholder="Nombre, código o correo"/></Campo><Campo etiqueta="Estado"><select value={estado} onChange={(e) => setEstado(e.target.value)}><option value="TODOS">Todos</option><option value="ENVIADO">Enviados</option><option value="PENDIENTE">Pendientes de envío</option><option value="SIN_CORREO">Sin correo</option></select></Campo><Campo etiqueta="Dependencia"><select value={dependencia} onChange={(e) => setDependencia(e.target.value)}><option value="TODAS">Todas</option><option>Monitores Aulas de Software</option><option>Monitores Laboratorios</option><option>Monitores Física</option></select></Campo></div></section><section className={`${estilos.tarjeta} ${estilos.tablaMemorandos}`}><header><div><h2>Memorandos generados</h2><p>El PDF está disponible aunque el envío esté pendiente.</p></div><span className={`${estilos.insignia} ${estilos.neutro}`}>{visibles.length} resultados</span></header><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Monitor</th><th>Retardos</th><th>Correo actual</th><th>Envío</th><th>PDF</th><th>Acciones</th></tr></thead><tbody>{visibles.map((item) => <tr key={item.id}><td><strong>{item.monitor}</strong><small>{item.codigo} · {item.dependencia}</small></td><td><span className={`${estilos.insignia} ${estilos.advertencia}`}>{item.retardos} retardos</span></td><td>{item.correo || "Sin correo"}{item.fechaEnvio && <small>Último envío: {item.fechaEnvio}</small>}</td><td><Estado estado={item.estado} fecha={item.fechaEnvio}/></td><td><button type="button" className={estilos.botonSecundario} onClick={() => setAviso(`PDF de ${item.monitor} preparado para descarga en modo demo.`)}>Abrir PDF</button></td><td><button type="button" className={estilos.botonSecundario} disabled={!item.correo} onClick={() => reenviar(item)}>Reenviar</button></td></tr>)}{!visibles.length && <tr className={estilos.filaVacia}><td colSpan={6}><span>No hay memorandos con estos filtros.</span></td></tr>}</tbody></table></div></section></div>;
}

function Campo({ etiqueta, ancho, children }: { etiqueta: string; ancho?: boolean; children: React.ReactNode }) { return <label className={ancho ? estilos.campoAncho : estilos.campo}><span>{etiqueta}</span>{children}</label>; }
function Metrica({ etiqueta, valor, tono }: { etiqueta: string; valor: number; tono: string }) { return <article className={`${estilos.metrica} ${estilos[tono]}`}><span>{etiqueta}</span><strong>{valor}</strong><small>Estado actual</small></article>; }
function Estado({ estado, fecha }: { estado: EstadoEnvio; fecha?: string }) { const clase = estado === "ENVIADO" ? estilos.exito : estado === "PENDIENTE" ? estilos.advertencia : estilos.neutro; const texto = estado === "ENVIADO" ? "Enviado" : estado === "PENDIENTE" ? "Pendiente" : "Sin correo"; return <><span className={`${estilos.insignia} ${clase}`}>{texto}</span>{fecha && <small>{fecha}</small>}</>; }
