"use client";
import { useMemo,useState,type FormEvent } from "react";
import { horariosIniciales,monitores } from "@/features/monitores/datos/datosMonitores";
import type { ResultadoImportacion } from "@/features/monitores/tipos/modelosMonitores";
import { usarPaginacion } from "@/features/monitores/ganchos/usarPaginacion";
import { Paginacion } from "./Paginacion";
import estilos from "./VistasMonitores.module.css";

export function GestionHorarios(){
 const [horarios,setHorarios]=useState(horariosIniciales);const [buscar,setBuscar]=useState("");const [dia,setDia]=useState("");const [importador,setImportador]=useState(false);const [resultado,setResultado]=useState<ResultadoImportacion|null>(null);
 const filtrados=useMemo(()=>horarios.filter((item)=>{const monitor=monitores.find((m)=>m.id===item.monitorId);return(!buscar||`${monitor?.nombre} ${monitor?.codigo}`.toLocaleLowerCase("es").includes(buscar.toLocaleLowerCase("es")))&&(!dia||item.dia===dia)}),[horarios,buscar,dia]);const paginacion=usarPaginacion(filtrados,10);
 return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Turnos semanales</span><h1>Horarios de monitores</h1><p>Listado administrativo e importación masiva desde Excel.</p></div><button className="button-primary" type="button" onClick={()=>setImportador(true)}>Importar horarios</button></section>{resultado&&<div className={`${estilos.aviso} ${estilos.avisoExito}`}>Importación de <strong>{resultado.archivo}</strong>: {resultado.monitoresProcesados} monitores, {resultado.horariosCreados} horarios creados y {resultado.reactivados} reactivados.</div>}<section className={estilos.metricas}><Metrica label="Horarios activos" valor={horarios.filter((i)=>i.activo).length} tono="verde"/><Metrica label="Monitores cubiertos" valor={new Set(horarios.map((i)=>i.monitorId)).size} tono="azul"/><Metrica label="Bloques semanales" valor={horarios.length} tono="violeta"/><Metrica label="Inactivos" valor={horarios.filter((i)=>!i.activo).length} tono="ambar"/></section><section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Buscar monitor</span><input value={buscar} onChange={(e)=>{setBuscar(e.target.value);paginacion.reiniciar()}} placeholder="Nombre o código estudiantil"/></label><label className={estilos.campo}><span>Día</span><select value={dia} onChange={(e)=>{setDia(e.target.value);paginacion.reiniciar()}}><option value="">Todos</option>{["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"].map((item)=><option key={item}>{item}</option>)}</select></label><button className={estilos.botonSecundario} type="button" onClick={()=>{setBuscar("");setDia("")}}>Limpiar</button></div><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Monitor</th><th>Dependencia</th><th>Día</th><th>Inicio</th><th>Fin</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{paginacion.visibles.map((horario)=>{const monitor=monitores.find((item)=>item.id===horario.monitorId)!;return <tr key={horario.id}><td><strong>{monitor.nombre}</strong><small>{monitor.codigo}</small></td><td>{monitor.dependencia}</td><td>{horario.dia}</td><td>{horario.horaInicio}</td><td>{horario.horaFin}</td><td><span className={`${estilos.insignia} ${horario.activo?estilos.exito:estilos.neutro}`}>{horario.activo?"Activo":"Inactivo"}</span></td><td><div className={estilos.accionesTabla}><button type="button" onClick={()=>setHorarios((actual)=>actual.map((item)=>item.id===horario.id?{...item,activo:!item.activo}:item))}>{horario.activo?"Desactivar":"Reactivar"}</button></div></td></tr>})}</tbody></table></div><Paginacion {...paginacion} total={filtrados.length}/></section>{importador&&<ImportadorHorarios onClose={()=>setImportador(false)} onResult={(valor)=>{setResultado(valor);setImportador(false)}}/>}</>;
}
function Metrica({label,valor,tono}:{label:string;valor:number;tono:string}){return <article className={`${estilos.metrica} ${estilos[tono]}`}><span>{label}</span><strong>{valor}</strong><small>Semestre 2026-3</small></article>}
function ImportadorHorarios({onClose,onResult}:{onClose:()=>void;onResult:(resultado:ResultadoImportacion)=>void}){const[archivo,setArchivo]=useState<File|null>(null);const[error,setError]=useState("");const enviar=(evento:FormEvent)=>{evento.preventDefault();if(!archivo)return;const extension=archivo.name.split(".").pop()?.toLowerCase();if(!["xlsx","xls"].includes(extension??"")){setError("El archivo debe ser Excel (.xlsx o .xls).");return;}onResult({archivo:archivo.name,monitoresProcesados:8,horariosCreados:14,reactivados:2,filasIgnoradas:1,monitoresNoEncontrados:[],monitoresNoAutorizados:[]})};return <div className={estilos.fondoModal} role="presentation"><section className={estilos.modal} role="dialog" aria-modal="true" aria-labelledby="titulo-importar-horarios"><header><div><span className={estilos.etiqueta}>Importación administrativa</span><h2 id="titulo-importar-horarios">Importar horarios desde Excel</h2><p>Los bloques consecutivos del mismo día se unirán automáticamente.</p></div><button type="button" aria-label="Cerrar" onClick={onClose}>×</button></header><form className={estilos.formulario} onSubmit={enviar}><div className={estilos.aviso}>El archivo debe contener bloques por monitor con las etiquetas <strong>NOMBRE</strong>, <strong>CODIGO</strong> y una columna <strong>DIA/HORA</strong>.</div><label className={estilos.zonaCarga}><span><strong>{archivo?.name??"Seleccione el archivo de horarios"}</strong>Ejemplo: MIÉRCOLES 12-14 + MIÉRCOLES 14-16 se importará como 12:00–16:00.</span><input type="file" accept=".xlsx,.xls" onChange={(e)=>{setArchivo(e.target.files?.[0]??null);setError("")}} required/></label>{error&&<div className={`${estilos.aviso} ${estilos.avisoError}`}>{error}</div>}<footer className={estilos.accionesFormulario}><button type="button" className={estilos.botonSecundario} onClick={onClose}>Volver</button><button type="submit" className="button-primary" disabled={!archivo}>Importar horarios</button></footer></form></section></div>}
