"use client";

import { useMemo, useState } from "react";
import { sesionesDemo } from "@/features/monitores/api/datosDemo";
import estilos from "./SistemaVisualMonitores.module.css";

export function HorasExtraPorAprobar() {
  const [sesiones, setSesiones] = useState(sesionesDemo.filter((item) => item.overtime_status === "pending"));
  const [monitor, setMonitor] = useState(""); const [fecha, setFecha] = useState(""); const [minimo, setMinimo] = useState(""); const [aviso, setAviso] = useState("");
  const visibles = useMemo(() => sesiones.filter((item) => (!monitor || item.monitor_name.toLowerCase().includes(monitor.toLowerCase())) && (!fecha || item.work_day === fecha) && (!minimo || item.overtime_minutes / 60 >= Number(minimo))), [sesiones, monitor, fecha, minimo]);
  const decidir = (id: string, decision: string) => { setSesiones((actual) => actual.filter((item) => item.id !== id)); setAviso(`Horas extra ${decision === "aprobar" ? "aprobadas" : "rechazadas"} correctamente en modo demo.`); };
  return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Control de novedades</span><h1>Horas extra por aprobar</h1><p>Revise y decida sobre el tiempo registrado fuera del turno asignado.</p></div><span className={`${estilos.insignia} ${estilos.advertencia}`}>{visibles.length} sesiones</span></section>{aviso && <div className={`${estilos.aviso} ${estilos.avisoExito}`}>{aviso}</div>}<section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Monitor</span><input value={monitor} onChange={(e) => setMonitor(e.target.value)} placeholder="Filtrar por monitor" /></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={fecha} onChange={(e) => setFecha(e.target.value)} /></label><label className={estilos.campo}><span>Horas extra por aprobar (h)</span><input type="number" min="0" step="0.25" value={minimo} onChange={(e) => setMinimo(e.target.value)} /></label><button className={estilos.botonSecundario} onClick={() => { setMonitor(""); setFecha(""); setMinimo(""); }}>Limpiar</button></div><div className={estilos.tablaContenedor}><table className={`${estilos.tabla} ${estilos.tablaHorasExtra}`}><thead><tr><th>Monitor</th><th>Fecha</th><th>Turno registrado</th><th>Horas extra</th><th>Decisión</th></tr></thead><tbody>{visibles.map((item) => <tr key={item.id}><td><strong>{item.monitor_name}</strong></td><td>{item.work_day}</td><td>{item.actual_start?.slice(0, 5) ?? "—"} – {item.actual_end?.slice(0, 5) ?? "—"}</td><td><strong>{(item.overtime_minutes / 60).toFixed(1)} h</strong></td><td><div className={estilos.accionesTabla}><button onClick={() => decidir(item.id, "aprobar")}>Aprobar</button><button className={estilos.eliminar} onClick={() => decidir(item.id, "rechazar")}>Rechazar</button></div></td></tr>)}{!visibles.length && <tr><td colSpan={5} className={estilos.vacio}>No hay horas extra pendientes con estos filtros.</td></tr>}</tbody></table></div></section></>;
}
