"use client";
import { useState, type FormEvent } from "react";
import estilos from "./VistasMonitores.module.css";

export function ImportacionAsistencia(){
  const [archivo,setArchivo]=useState<File|null>(null);const [cargando,setCargando]=useState(false);const [resultado,setResultado]=useState<{procesados:number;pendientes:number;ignorados:number}|null>(null);const [error,setError]=useState("");
  const enviar=(evento:FormEvent)=>{evento.preventDefault();if(!archivo)return;const extension=archivo.name.split(".").pop()?.toLowerCase();if(!["xlsx","xls"].includes(extension??"")){setError("Seleccione un archivo Excel .xlsx o .xls.");return;}setError("");setCargando(true);window.setTimeout(()=>{setCargando(false);setResultado({procesados:46,pendientes:4,ignorados:2});},650)};
  return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Asistencia Croschex</span><h1>Importar asistencia</h1><p>Cargue manualmente un archivo Excel para procesar marcaciones.</p></div></section><div className={estilos.aviso}>Los líderes solo pueden subir registros de su propia dependencia, según la columna <strong>Departamento</strong> del archivo.</div><section className={estilos.tarjeta}><header><div><h2>Carga manual de Excel</h2><p>El archivo se valida antes de enviarse al servicio de importación.</p></div></header><form className={estilos.formulario} onSubmit={enviar}><label className={estilos.zonaCarga}><span><strong>{archivo?.name??"Seleccione el archivo de marcaciones"}</strong>Formatos admitidos: XLSX y XLS · máximo 10 MB</span><input type="file" accept=".xlsx,.xls" onChange={(e)=>{setArchivo(e.target.files?.[0]??null);setResultado(null);setError("")}} required/></label>{error&&<div className={`${estilos.aviso} ${estilos.avisoError}`}>{error}</div>}<div className={estilos.accionesFormulario}><button className="button-primary" type="submit" disabled={!archivo||cargando}>{cargando?"Procesando…":"Subir archivo"}</button></div></form>{resultado&&<div className={estilos.contenido}><div className={`${estilos.aviso} ${estilos.avisoExito}`}>Importación completada. Revise los registros pendientes en Conciliación.</div><div className={estilos.resultadoImportacion}><span><b>{resultado.procesados}</b>Procesados</span><span><b>{resultado.pendientes}</b>Por conciliar</span><span><b>{resultado.ignorados}</b>Ignorados</span><span><b>{resultado.procesados+resultado.pendientes+resultado.ignorados}</b>Total de filas</span></div></div>}</section></>;
}
