"use client";

import { useMemo, useState } from "react";
import { conciliacionesDemo, monitoresDemo } from "@/features/monitores/api/datosDemo";
import estilos from "./SistemaVisualMonitores.module.css";

export function InconsistenciasAsistencia() {
  const [registros, setRegistros] = useState(conciliacionesDemo); const [buscar, setBuscar] = useState(""); const [fecha, setFecha] = useState(""); const [aviso, setAviso] = useState("");
  const visibles = useMemo(() => registros.filter((item) => (!buscar || `${item.raw_full_name} ${item.raw_department} ${item.manual_review_reason}`.toLowerCase().includes(buscar.toLowerCase())) && (!fecha || item.work_day === fecha)), [registros, buscar, fecha]);
  const vincular = (id: string) => { setRegistros((actual) => actual.filter((item) => item.id !== id)); setAviso("Registro vinculado correctamente; ya no aparece como inconsistencia."); };
  return <><section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Control de asistencia</span><h1>Inconsistencias de asistencia</h1><p>Revise las marcaciones que no se asociaron automáticamente y asígnelas al monitor correspondiente.</p></div><span className={`${estilos.insignia} ${estilos.advertencia}`}>{visibles.length} pendientes</span></section>{aviso && <div className={`${estilos.aviso} ${estilos.avisoExito}`}>{aviso}</div>}<section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Búsqueda</span><input value={buscar} onChange={(e) => setBuscar(e.target.value)} placeholder="Nombre, dependencia o motivo" /></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={fecha} onChange={(e) => setFecha(e.target.value)} /></label><button className={estilos.botonSecundario} onClick={() => { setBuscar(""); setFecha(""); }}>Limpiar</button></div><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Nombre registrado</th><th>Dependencia</th><th>Fecha</th><th>Motivo</th><th>Asignar monitor</th></tr></thead><tbody>{visibles.map((item) => <tr key={item.id}><td><strong>{item.raw_full_name}</strong></td><td>{item.raw_department}</td><td>{item.work_day}</td><td>{item.manual_review_reason || item.processing_error || "Coincidencia no encontrada"}</td><td><div className={estilos.accionesTabla}><select aria-label="Monitor a asignar" defaultValue=""><option value="">Seleccione</option>{monitoresDemo.map((monitor) => <option key={monitor.id}>{monitor.full_name}</option>)}</select><button onClick={() => vincular(item.id)}>Vincular</button></div></td></tr>)}{!visibles.length && <tr><td colSpan={5} className={estilos.vacio}>No hay inconsistencias con estos filtros.</td></tr>}</tbody></table></div></section></>;
}
