"use client";

import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { adaptarMonitor } from "@/features/monitores/api/adaptadoresMonitores";
import { servicioMonitores } from "@/features/monitores/api/servicioMonitores";
import type { DashboardApi, MonitorApi } from "@/features/monitores/api/contratosMonitores";
import estilos from "./SistemaVisualMonitores.module.css";
import { AvisoTemporal } from "./AvisoTemporal";

type FormMonitor = { full_name: string; codigo_estudiante: string; email: string; department: string; numero_documento: string; proyecto_curricular: string; telefono: string; confirm_repeating_monitor: boolean };
const vacio: FormMonitor = { full_name: "", codigo_estudiante: "", email: "", department: "informatics_labs", numero_documento: "", proyecto_curricular: "", telefono: "", confirm_repeating_monitor: false };
const soloNumeros = (valor: string) => valor.replace(/\D/g, "");

function FormularioMonitor({ form, onChange, texto, guardando }: { form: FormMonitor; onChange: (form: FormMonitor) => void; texto: string; guardando: boolean }) {
  return <div className={estilos.formulario}>
    <label className={estilos.campo}><span>Nombre completo</span><input required value={form.full_name} onChange={(e) => onChange({ ...form, full_name: e.target.value })} /></label>
    <label className={estilos.campo}><span>Código estudiantil</span><input required inputMode="numeric" pattern="[0-9]+" value={form.codigo_estudiante} onChange={(e) => onChange({ ...form, codigo_estudiante: soloNumeros(e.target.value) })} /></label>
    <label className={estilos.campo}><span>Correo institucional</span><input required type="email" value={form.email} onChange={(e) => onChange({ ...form, email: e.target.value })} /></label>
    <div className={estilos.formularioDoble}><label className={estilos.campo}><span>Número de documento</span><input required inputMode="numeric" pattern="[0-9]+" value={form.numero_documento} onChange={(e) => onChange({ ...form, numero_documento: soloNumeros(e.target.value) })} /></label><label className={estilos.campo}><span>Teléfono</span><input required inputMode="numeric" pattern="[0-9]+" value={form.telefono} onChange={(e) => onChange({ ...form, telefono: soloNumeros(e.target.value) })} /></label></div>
    <label className={estilos.campo}><span>Proyecto curricular</span><select required value={form.proyecto_curricular} onChange={(e) => onChange({ ...form, proyecto_curricular: e.target.value })}><option value="">Seleccione un proyecto curricular</option><option value="ingenieria_electronica">Ingeniería electrónica</option><option value="ingenieria_sistemas">Ingeniería de sistemas</option><option value="ingenieria_electrica">Ingeniería eléctrica</option><option value="ingenieria_industrial">Ingeniería industrial</option><option value="ingenieria_catastral">Ingeniería catastral</option><option value="licenciatura_fisica">Licenciatura en Física</option></select></label>
    <label className={estilos.campo}><span>Dependencia</span><select required value={form.department} onChange={(e) => onChange({ ...form, department: e.target.value })}><option value="informatics_labs">Monitores Aulas de Software</option><option value="electrical">Monitores Laboratorios</option><option value="physics">Monitores Fisica</option></select></label>
    <label className={estilos.verificacion}><input type="checkbox" checked={form.confirm_repeating_monitor} onChange={(e) => onChange({ ...form, confirm_repeating_monitor: e.target.checked })} />Confirmo que este monitor ya hizo monitorías y repetirá en el semestre actual</label>
    <button className="button-primary" disabled={guardando}>{guardando ? "Procesando…" : texto}</button>
  </div>;
}

export function MonitoresApiView() {
  const [rows, setRows] = useState<MonitorApi[]>([]); const [form, setForm] = useState(vacio); const [buscar, setBuscar] = useState(""); const [estado, setEstado] = useState("TODOS");
  const [alertasPorMonitor, setAlertasPorMonitor] = useState<Record<string, Pick<DashboardApi["monitor_rows"][number], "late_count" | "memorandums_count">>>({});
  const [error, setError] = useState(""); const [aviso, setAviso] = useState(""); const [cargando, setCargando] = useState(true); const [guardando, setGuardando] = useState(false);
  const [archivo, setArchivo] = useState<File | null>(null); const [confirmarCarga, setConfirmarCarga] = useState(false); const [resultadoCarga, setResultadoCarga] = useState<{ total_rows: number; created: number; skipped: unknown[]; errors: unknown[] } | null>(null);
  const [edicion, setEdicion] = useState<MonitorApi | null>(null); const [formEdicion, setFormEdicion] = useState(vacio); const [eliminando, setEliminando] = useState<MonitorApi | null>(null); const [contrasena, setContrasena] = useState(""); const [semestreModal, setSemestreModal] = useState(false); const [nuevoSemestre, setNuevoSemestre] = useState(""); const [impacto, setImpacto] = useState<Record<string, number> | null>(null);
  const crearRef = useRef<HTMLElement | null>(null); const cargaRef = useRef<HTMLElement | null>(null);
  const fallo = (e: unknown, fallback: string) => setError(e instanceof Error ? e.message : fallback);
  async function cargar() { setCargando(true); setError(""); try { const [monitores, dashboard] = await Promise.all([servicioMonitores.listarMonitores(), servicioMonitores.obtenerDashboard()]); setRows(monitores); setAlertasPorMonitor(Object.fromEntries(dashboard.monitor_rows.map((fila) => [fila.monitor_id, { late_count: fila.late_count, memorandums_count: fila.memorandums_count }]))); } catch (e) { fallo(e, "No fue posible cargar los monitores."); } finally { setCargando(false); } }
  useEffect(() => { void cargar(); }, []);
  const visibles = useMemo(() => rows.filter((item) => { const texto = `${item.full_name} ${item.codigo_estudiante} ${item.user_email ?? ""}`.toLocaleLowerCase("es"); return (!buscar || texto.includes(buscar.toLocaleLowerCase("es"))) && (estado === "TODOS" || (estado === "ACTIVOS" ? item.is_active : !item.is_active)); }), [rows, buscar, estado]);
  async function crear(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); setGuardando(true); setError(""); try { const creado = await servicioMonitores.provisionarMonitor(form); setRows((actual) => [creado, ...actual]); setForm(vacio); setAviso(creado.activation_email_sent ? "Monitor creado. Se envió el correo de activación." : "Monitor creado, pero no fue posible enviar la activación. Usa Reenviar correo cuando se restablezca el correo saliente."); } catch (e) { fallo(e, "No fue posible crear el monitor."); } finally { setGuardando(false); } }
  async function alternar(item: MonitorApi) { try { const actualizado = await servicioMonitores.actualizarMonitor(item.id, { is_active: !item.is_active }); setRows((actual) => actual.map((row) => row.id === item.id ? actualizado : row)); } catch (e) { fallo(e, "No fue posible actualizar el estado."); } }
  async function importar(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); if (!archivo) { setError("Selecciona un archivo Excel (.xlsx)."); return; } setGuardando(true); setError(""); try { const resultado = await servicioMonitores.importarMonitores(archivo, confirmarCarga); setResultadoCarga(resultado); setAviso(`Carga finalizada: ${resultado.created} monitor(es) creado(s).`); await cargar(); } catch (e) { fallo(e, "No fue posible procesar el archivo."); } finally { setGuardando(false); } }
  function abrirEdicion(item: MonitorApi) { setEdicion(item); setFormEdicion({ full_name: item.full_name, codigo_estudiante: item.codigo_estudiante, email: item.user_email ?? "", department: item.department, numero_documento: item.numero_documento ?? "", proyecto_curricular: item.proyecto_curricular ?? "", telefono: item.telefono ?? "", confirm_repeating_monitor: false }); }
  async function guardarEdicion(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); if (!edicion) return; setGuardando(true); try { const actualizado = await servicioMonitores.editarCuentaMonitor(edicion.id, formEdicion); setRows((actual) => actual.map((row) => row.id === actualizado.id ? actualizado : row)); setEdicion(null); setAviso("Datos del monitor actualizados."); } catch (e) { fallo(e, "No fue posible editar el monitor."); } finally { setGuardando(false); } }
  async function reenviar(item: MonitorApi) { try { const respuesta = await servicioMonitores.reenviarActivacion(item.id); setAviso(respuesta.detail); } catch (e) { fallo(e, "No fue posible reenviar el correo."); } }
  async function confirmarEliminacion(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); if (!eliminando) return; setGuardando(true); try { const validacion = await servicioMonitores.verificarContrasenaActual(contrasena); if (!validacion.valido) { setError("La contraseña no es válida."); return; } await servicioMonitores.eliminarMonitor(eliminando.id); setRows((actual) => actual.filter((row) => row.id !== eliminando.id)); setEliminando(null); setContrasena(""); setAviso("Monitor eliminado correctamente."); } catch (e) { fallo(e, "No fue posible eliminar el monitor."); } finally { setGuardando(false); } }
  async function abrirSemestre() { setError(""); try { const datos = await servicioMonitores.previsualizarNuevoSemestre(); setImpacto(datos.preview); setSemestreModal(true); } catch (e) { fallo(e, "No fue posible preparar el inicio de semestre."); } }
  async function iniciarSemestre(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); setGuardando(true); try { const resultado = await servicioMonitores.iniciarNuevoSemestre(nuevoSemestre); setSemestreModal(false); setNuevoSemestre(""); setAviso(`Se inició el semestre ${resultado.new_semester}. Los registros históricos se conservaron.`); await cargar(); } catch (e) { fallo(e, "No fue posible iniciar el semestre."); } finally { setGuardando(false); } }
  return <div className={estilos.gestionCuentas}>
    <section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Gestión académica</span><h1>Monitores</h1><p>Administre cuentas, activaciones y la carga masiva del semestre.</p></div><div className={estilos.encabezadoAcciones}><button type="button" className={estilos.botonSecundario} onClick={() => cargaRef.current?.scrollIntoView({ behavior: "smooth" })}>Cargar Excel</button><button type="button" className={estilos.botonSecundario} onClick={() => void abrirSemestre()}>Iniciar semestre nuevo</button><button type="button" className="button-primary" onClick={() => crearRef.current?.scrollIntoView({ behavior: "smooth" })}>Nuevo monitor</button></div></section>
    <section className={estilos.metricas}><article className={`${estilos.metrica} ${estilos.violeta}`}><span>Total</span><strong>{rows.length}</strong><small>Registros en la API</small></article><article className={`${estilos.metrica} ${estilos.verde}`}><span>Activos</span><strong>{rows.filter((item) => item.is_active).length}</strong><small>Disponibles para gestión</small></article><article className={`${estilos.metrica} ${estilos.ambar}`}><span>Inactivos</span><strong>{rows.filter((item) => !item.is_active).length}</strong><small>Sin operación vigente</small></article><article className={`${estilos.metrica} ${estilos.azul}`}><span>Visibles</span><strong>{visibles.length}</strong><small>Según filtros actuales</small></article></section>
    {error && <AvisoTemporal mensaje={error} tipo="error" alCerrar={() => setError("")} />}{aviso && <AvisoTemporal mensaje={aviso} tipo="exito" alCerrar={() => setAviso("")} />}
    <div className={estilos.distribucionFormulario}><div className={estilos.columnaFormularios}><section ref={crearRef} className={`${estilos.tarjeta} ${estilos.formularioFijo}`}><header><div><h2>Crear monitor</h2><p>La cuenta se crea sin contraseña y recibe un enlace para activar su acceso.</p></div></header><form onSubmit={crear}><FormularioMonitor form={form} onChange={setForm} texto="+ Crear y enviar activación" guardando={guardando} /></form></section><section ref={cargaRef} className={`${estilos.tarjeta} ${estilos.cargaMasivaCuentas}`}><header><div><h2>Carga masiva</h2><p>Puedes usar encabezados en inglés o español.</p></div></header><form className={estilos.formularioCargaMasiva} onSubmit={importar}><div className={estilos.especificacionArchivo}><p><strong>Requeridos:</strong></p><ul><li>email / correo</li><li>full_name / nombre completo</li><li>codigo_estudiante / codigo estudiante</li><li>department / dependencia (<strong>Monitores Aulas de Software, Monitores Laboratorios, Monitores Fisica</strong>)</li></ul><p><strong>Opcionales:</strong></p><ul><li>numero_documento / numero documento</li><li>proyecto_curricular / proyecto curricular (ingenieria_electronica, ingenieria_sistemas, ingenieria_electrica, ingenieria_industrial, ingenieria_catastral, licenciatura_fisica)</li><li>telefono / phone</li></ul></div><label className={estilos.archivoCarga}>Archivo Excel (.xlsx)<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e) => setArchivo(e.target.files?.[0] ?? null)} /><small>{archivo?.name ?? "Ningún archivo seleccionado"}</small></label><label className={estilos.confirmacionCarga}><input type="checkbox" checked={confirmarCarga} onChange={(e) => setConfirmarCarga(e.target.checked)} />Confirmo que los monitores con historial en este archivo repetirán monitorías</label><button className="button-primary" disabled={guardando}>↑ Procesar archivo</button>{resultadoCarga && <div className={estilos.resultadoImportacion}><span><b>{resultadoCarga.total_rows}</b>Filas</span><span><b>{resultadoCarga.created}</b>Creados</span><span><b>{resultadoCarga.skipped.length}</b>Omitidos</span><span><b>{resultadoCarga.errors.length}</b>Con error</span></div>}</form></section></div>
      <section className={`${estilos.tarjeta} ${estilos.listadoCuentas}`}><header><div><h2>Directorio de monitores</h2><p>Gestione cada cuenta y su activación.</p></div><button type="button" className={estilos.botonSecundario} onClick={() => void cargar()} disabled={cargando}>Actualizar</button></header><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Buscar</span><input value={buscar} onChange={(e) => setBuscar(e.target.value)} placeholder="Nombre, código o correo" /></label><label className={estilos.campo}><span>Estado</span><select value={estado} onChange={(e) => setEstado(e.target.value)}><option value="TODOS">Todos</option><option value="ACTIVOS">Activos</option><option value="INACTIVOS">Inactivos</option></select></label></div><div className={estilos.tablaContenedor}><table className={`${estilos.tabla} ${estilos.tablaCuentas}`}><thead><tr><th>Nombre</th><th>Código</th><th>Correo</th><th>Dependencia</th><th>Alertas</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{cargando ? <tr><td colSpan={7} className={estilos.vacio}>Cargando monitores…</td></tr> : visibles.map((item) => { const alertas = alertasPorMonitor[item.id] ?? { late_count: 0, memorandums_count: 0 }; return <tr key={item.id}><td><strong>{item.full_name}</strong><small>{item.proyecto_curricular?.replaceAll("_", " ") || "Programa no registrado"}</small></td><td>{item.codigo_estudiante}<small>Doc. {item.numero_documento || "No registrado"}</small></td><td className={estilos.correoCuenta}>{item.user_email || "Sin correo vinculado"}<small>{item.telefono || "Sin teléfono"}</small></td><td>{adaptarMonitor(item).dependencia}</td><td><span className={`${estilos.insignia} ${alertas.late_count ? estilos.advertencia : estilos.exito}`}>{alertas.late_count} retardo{alertas.late_count === 1 ? "" : "s"}</span><small>{alertas.memorandums_count} memorando{alertas.memorandums_count === 1 ? "" : "s"}</small></td><td><span className={`${estilos.insignia} ${item.is_active ? estilos.exito : estilos.neutro}`}>{item.is_active ? "Activo" : "Inactivo"}</span></td><td><div className={estilos.accionesCuenta}><button type="button" onClick={() => abrirEdicion(item)}>Editar</button><button type="button" onClick={() => void reenviar(item)}>Reenviar correo</button><button type="button" onClick={() => void alternar(item)}>{item.is_active ? "Desactivar" : "Activar"}</button><button type="button" className={`${estilos.eliminar} ${estilos.eliminarMonitor}`} aria-label={`Eliminar a ${item.full_name}`} onClick={() => setEliminando(item)}>🗑 Eliminar</button></div></td></tr>; })}{!cargando && !visibles.length && <tr><td colSpan={7} className={estilos.vacio}>No hay monitores registrados o coincidentes.</td></tr>}</tbody></table></div></section></div>
    {edicion && <div className={estilos.fondoModal}><section className={estilos.modal} role="dialog" aria-modal="true"><header><div><h2>Editar monitor</h2><p>Actualice los datos de {edicion.full_name}.</p></div><button type="button" onClick={() => setEdicion(null)}>×</button></header><form onSubmit={guardarEdicion}><FormularioMonitor form={formEdicion} onChange={setFormEdicion} texto="Guardar cambios" guardando={guardando} /></form></section></div>}
    {eliminando && <div className={estilos.fondoModal}><section className={estilos.modal} role="dialog" aria-modal="true"><header><div><h2>Eliminar monitor</h2><p>Esta acción elimina la cuenta de {eliminando.full_name}.</p></div><button type="button" onClick={() => setEliminando(null)}>×</button></header><form className={estilos.formulario} onSubmit={confirmarEliminacion}><p>Escribe tu contraseña actual para confirmar la eliminación.</p><label className={estilos.campo}><span>Contraseña</span><input required type="password" autoComplete="current-password" value={contrasena} onChange={(e) => setContrasena(e.target.value)} /></label><button className={estilos.botonConfirmarEliminacion} disabled={guardando}>{guardando ? "Eliminando…" : "Eliminar monitor"}</button></form></section></div>}
    {semestreModal && <div className={estilos.fondoModal}><section className={estilos.modal} role="dialog" aria-modal="true"><header><div><h2>Iniciar semestre nuevo</h2><p>Esta operación archiva el semestre actual y desactiva monitores y horarios vigentes.</p></div><button type="button" onClick={() => setSemestreModal(false)}>×</button></header><form className={estilos.formulario} onSubmit={iniciarSemestre}>{impacto && <div className={estilos.resultadoImportacion}>{Object.entries(impacto).slice(0, 4).map(([clave, valor]) => <span key={clave}><b>{valor}</b>{clave.replaceAll("_", " ")}</span>)}</div>}<label className={estilos.campo}><span>Nombre del nuevo semestre</span><input required placeholder="Ej.: 2026-3" value={nuevoSemestre} onChange={(e) => setNuevoSemestre(e.target.value)} /></label><button className="button-primary" disabled={guardando}>Confirmar inicio de semestre</button></form></section></div>}
  </div>;
}
