"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { adaptarMonitor, adaptarResumenDashboard, nombreDependencia } from "@/features/monitores/api/adaptadoresMonitores";
import type { ConciliacionApi, DashboardApi, MonitorApi } from "@/features/monitores/api/contratosMonitores";
import { servicioMonitores } from "@/features/monitores/api/servicioMonitores";
import { usarRecursoApi } from "@/features/monitores/ganchos/usarRecursoApi";
import { BusquedaPorCodigo } from "./BusquedaPorCodigo";
import estilos from "./SistemaVisualMonitores.module.css";

export function PanelLider() {
  const tablero=usarRecursoApi(servicioMonitores.obtenerDashboard,{monitor_rows:[],pending_overtime:[],recent_annotations:[],notifications:[]} as DashboardApi);const recursoMonitores=usarRecursoApi(servicioMonitores.listarMonitores,[] as MonitorApi[]);const conciliaciones=usarRecursoApi(servicioMonitores.listarConciliaciones,[] as ConciliacionApi[]);const [cerradas,setCerradas]=useState<string[]>([]);const [paginas,setPaginas]=useState<Record<string,number>>({});
  const monitores=useMemo(()=>recursoMonitores.datos.map(adaptarMonitor),[recursoMonitores.datos]);const resumenes=useMemo(()=>adaptarResumenDashboard(tablero.datos.monitor_rows),[tablero.datos.monitor_rows]);const dependencias=[...new Set(monitores.map((item)=>item.dependencia))];const horas=resumenes.reduce((total,item)=>total+item.horasNormales+item.horasExtraAprobadas+item.horasAnotaciones,0);const error=tablero.error||recursoMonitores.error||conciliaciones.error;
  return <>
    <section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Gestión de monitores</span><h1>Dashboard de líder</h1><p>Seguimiento de horas, conciliaciones y novedades por dependencia.</p></div><div className={estilos.encabezadoAcciones}><Link className={estilos.botonSecundario} href="/gestion-monitores/excepciones">Gestionar excepciones</Link><Link className="button-primary" href="/gestion-monitores/anotaciones">Gestionar anotaciones</Link></div></section>
    {error&&<div className={`${estilos.aviso} ${estilos.avisoError}`}>{error}</div>}
    <section className={estilos.metricas}><Metrica label="Monitores visibles" valor={monitores.length} detalle={`${dependencias.length} dependencias`} tono="verde"/><Metrica label="Horas acumuladas" valor={horas.toFixed(1)} detalle="Total neto" tono="azul"/><Metrica label="Extra pendientes" valor={tablero.datos.pending_overtime.length} detalle="Requieren decisión" tono="ambar"/><Metrica label="Por conciliar" valor={conciliaciones.datos.length} detalle="Registros crudos" tono="violeta"/></section>
    <BusquedaPorCodigo />
    <div className={estilos.rejillaPrincipal}><div className={estilos.columnaPrincipal}><section className={estilos.tarjeta}><header><div><h2>Horas por monitor</h2><p>Meta semestral de 192 horas y paginación independiente por dependencia.</p></div><span className={`${estilos.insignia} ${estilos.neutro}`}>{monitores.length} monitores</span></header><div className={estilos.resumenMonitores}>{dependencias.map((dependencia)=>{const grupo=monitores.filter((item)=>item.dependencia===dependencia);const pagina=paginas[dependencia]??1;const porPagina=3;const totalPaginas=Math.ceil(grupo.length/porPagina);return <article className={estilos.bloqueDependencia} key={dependencia}><button type="button" onClick={()=>setCerradas((actual)=>actual.includes(dependencia)?actual.filter((item)=>item!==dependencia):[...actual,dependencia])}><strong>{cerradas.includes(dependencia)?"▸":"▾"} {dependencia}</strong><span>{grupo.length} monitor(es)</span></button>{!cerradas.includes(dependencia)&&<>{grupo.slice((pagina-1)*porPagina,pagina*porPagina).map((monitor)=>{const resumen=resumenes.find((item)=>item.monitorId===monitor.id);if(!resumen)return null;const total=resumen.horasNormales+resumen.horasExtraAprobadas+resumen.horasAnotaciones;return <div className={estilos.filaResumen} key={monitor.id}><strong>{monitor.nombre}<small>{monitor.codigo}</small></strong><span>{resumen.horasNormales.toFixed(1)} normales</span><span>{resumen.horasExtraAprobadas.toFixed(1)} extra</span><span>{resumen.horasExtraPendientes.toFixed(1)} pendientes</span><span>{resumen.horasAnotaciones.toFixed(1)} ajustes</span><span>{total.toFixed(1)} total</span><span>{Math.max(0,192-total).toFixed(1)} faltan</span><Link href={`/gestion-monitores/registros/${monitor.id}`}>Ver registros</Link></div>})}<footer className={estilos.pieGrupo}><span>Página {pagina} de {Math.max(totalPaginas,1)}</span><div className={estilos.accionesTabla}><button type="button" disabled={pagina<=1} onClick={()=>setPaginas((actual)=>({...actual,[dependencia]:pagina-1}))}>Anterior</button><button type="button" disabled={pagina>=totalPaginas} onClick={()=>setPaginas((actual)=>({...actual,[dependencia]:pagina+1}))}>Siguiente</button></div></footer></>}</article>})}</div></section>
    <section className={estilos.tarjeta}><header><div><h2>Registros por conciliar</h2><p>Marcaciones que requieren asignación manual.</p></div></header><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Nombre crudo</th><th>Dependencia</th><th>Fecha</th><th>Estado</th><th>Motivo</th></tr></thead><tbody>{conciliaciones.datos.slice(0,6).map((registro)=><tr key={registro.id}><td><strong>{registro.raw_full_name}</strong></td><td>{nombreDependencia(registro.raw_department)}</td><td>{registro.work_day}</td><td><span className={`${estilos.insignia} ${estilos.advertencia}`}>PENDIENTE</span></td><td>{registro.manual_review_reason||registro.processing_error||"Sin coincidencia"}</td></tr>)}</tbody></table></div></section></div>
    <aside className={estilos.columnaLateral}><TarjetaLateral titulo="Horas extra por aprobar" elementos={tablero.datos.pending_overtime.slice(0,4).map((item)=>({titulo:item.monitor_name,texto:`${item.work_day} · ${(item.overtime_minutes/60).toFixed(1)} h por aprobar`}))}/><TarjetaLateral titulo="Notificaciones" elementos={tablero.datos.notifications.map((item)=>({titulo:item.title,texto:item.body}))}/><TarjetaLateral titulo="Anotaciones recientes" elementos={tablero.datos.recent_annotations.slice(0,4).map((item)=>({titulo:item.monitor_name,texto:`${item.action==="add"?"+":item.action==="deduct"?"−":""}${Math.abs(item.delta_minutes/60).toFixed(1)} h · ${item.occurred_on}`}))}/></aside></div>
  </>;
}
function Metrica({label,valor,detalle,tono}:{label:string;valor:string|number;detalle:string;tono:string}){return <article className={`${estilos.metrica} ${estilos[tono]}`}><span>{label}</span><strong>{valor}</strong><small>{detalle}</small></article>}
function TarjetaLateral({titulo,elementos}:{titulo:string;elementos:Array<{titulo:string;texto:string}>}){return <section className={estilos.tarjeta}><header><h2>{titulo}</h2></header><div className={estilos.listaLateral}>{elementos.length?elementos.map((item,index)=><article key={`${titulo}-${index}`}><strong>{item.titulo}</strong><span>{item.texto}</span></article>):<span className={estilos.vacio}>Sin registros.</span>}</div></section>}
