"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { anotacionesIniciales, monitores, notificacionesIniciales, registrosCrudosIniciales, resumenesIniciales, sesionesIniciales } from "@/features/monitores/datos/datosMonitores";
import estilos from "./VistasMonitores.module.css";

export function PanelLider() {
  const dependencias = [...new Set(monitores.map((item) => item.dependencia))];
  const [cerradas, setCerradas] = useState<string[]>([]);
  const [paginas, setPaginas] = useState<Record<string,number>>({});
  const pendientes = sesionesIniciales.filter((item) => item.estadoExtra === "PENDIENTE");
  const totales = useMemo(() => ({ monitores:monitores.length, pendientes:pendientes.length, conciliacion:registrosCrudosIniciales.filter((item) => item.estado === "PENDIENTE").length, horas:resumenesIniciales.reduce((total,item) => total + item.horasNormales + item.horasExtraAprobadas + item.horasAnotaciones,0) }), [pendientes.length]);
  return <>
    <section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Gestión de monitores</span><h1>Dashboard de líder</h1><p>Seguimiento de horas, conciliaciones y novedades por dependencia.</p></div><div className={estilos.encabezadoAcciones}><Link className={estilos.botonSecundario} href="/gestion-monitores/excepciones">Gestionar excepciones</Link><Link className="button-primary" href="/gestion-monitores/anotaciones">Gestionar anotaciones</Link></div></section>
    <section className={estilos.metricas}><Metrica label="Monitores visibles" valor={totales.monitores} detalle="3 dependencias" tono="verde"/><Metrica label="Horas acumuladas" valor={totales.horas.toFixed(1)} detalle="Total neto" tono="azul"/><Metrica label="Extra pendientes" valor={totales.pendientes} detalle="Requieren decisión" tono="ambar"/><Metrica label="Por conciliar" valor={totales.conciliacion} detalle="Registros crudos" tono="violeta"/></section>
    <div className={estilos.rejillaPrincipal}><div className={estilos.columnaPrincipal}><section className={estilos.tarjeta}><header><div><h2>Horas por monitor</h2><p>Meta semestral de 192 horas y paginación independiente por dependencia.</p></div><span className={`${estilos.insignia} ${estilos.neutro}`}>{monitores.length} monitores</span></header><div className={estilos.resumenMonitores}>{dependencias.map((dependencia) => { const grupo = monitores.filter((item) => item.dependencia === dependencia); const pagina = paginas[dependencia] ?? 1; const porPagina=3; const totalPaginas=Math.ceil(grupo.length/porPagina); return <article className={estilos.bloqueDependencia} key={dependencia}><button type="button" onClick={() => setCerradas((actual) => actual.includes(dependencia) ? actual.filter((item) => item !== dependencia) : [...actual,dependencia])}><strong>{cerradas.includes(dependencia) ? "▸" : "▾"} {dependencia}</strong><span>{grupo.length} monitor(es)</span></button>{!cerradas.includes(dependencia) && <>{grupo.slice((pagina-1)*porPagina,pagina*porPagina).map((monitor) => { const resumen=resumenesIniciales.find((item) => item.monitorId===monitor.id)!; const total=resumen.horasNormales+resumen.horasExtraAprobadas+resumen.horasAnotaciones; return <div className={estilos.filaResumen} key={monitor.id}><strong>{monitor.nombre}<small>{monitor.codigo}</small></strong><span>{resumen.horasNormales.toFixed(1)} normales</span><span>{resumen.horasExtraAprobadas.toFixed(1)} extra</span><span>{resumen.horasExtraPendientes.toFixed(1)} pendientes</span><span>{resumen.horasAnotaciones.toFixed(1)} ajustes</span><span>{total.toFixed(1)} total</span><span>{Math.max(0,192-total).toFixed(1)} faltan</span><Link href={`/gestion-monitores/registros/${monitor.id}`}>Ver registros</Link></div>})}<footer className={estilos.pieGrupo}><span>Página {pagina} de {Math.max(totalPaginas,1)}</span><div className={estilos.accionesTabla}><button type="button" disabled={pagina<=1} onClick={() => setPaginas((actual) => ({...actual,[dependencia]:pagina-1}))}>Anterior</button><button type="button" disabled={pagina>=totalPaginas} onClick={() => setPaginas((actual) => ({...actual,[dependencia]:pagina+1}))}>Siguiente</button><button type="button">Generar Excel</button></div></footer></>}</article>; })}</div></section>
    <section className={estilos.tarjeta}><header><div><h2>Historial reciente de registros</h2><p>Últimas marcaciones importadas desde Croschex.</p></div></header><div className={estilos.tablaContenedor}><table className={estilos.tabla}><thead><tr><th>Nombre crudo</th><th>Dependencia</th><th>Fecha</th><th>Estado</th><th>Monitor</th></tr></thead><tbody>{registrosCrudosIniciales.map((registro) => <tr key={registro.id}><td><strong>{registro.nombreOriginal}</strong></td><td>{registro.dependencia}</td><td>{registro.fecha}</td><td><span className={`${estilos.insignia} ${registro.estado === "CONCILIADO" ? estilos.exito : estilos.advertencia}`}>{registro.estado}</span></td><td>{monitores.find((item) => item.id === registro.monitorId)?.nombre ?? "—"}</td></tr>)}</tbody></table></div></section></div>
    <aside className={estilos.columnaLateral}><TarjetaLateral titulo="Horas extra por aprobar" elementos={pendientes.slice(0,4).map((item) => ({ titulo:monitores.find((monitor) => monitor.id===item.monitorId)?.nombre ?? "Monitor", texto:`${item.fecha} · ${item.horasExtra.toFixed(1)} h por aprobar` }))}/><TarjetaLateral titulo="Notificaciones" elementos={notificacionesIniciales.map((item) => ({titulo:item.titulo,texto:item.texto}))}/><TarjetaLateral titulo="Anotaciones recientes" elementos={anotacionesIniciales.slice(0,4).map((item) => ({titulo:monitores.find((monitor) => monitor.id===item.monitorId)?.nombre ?? "Monitor",texto:`${item.accion === "SUMAR" ? "+" : "−"}${item.horas} h · ${item.fecha}`}))}/></aside></div>
  </>;
}
function Metrica({label,valor,detalle,tono}:{label:string;valor:string|number;detalle:string;tono:string}){return <article className={`${estilos.metrica} ${estilos[tono]}`}><span>{label}</span><strong>{valor}</strong><small>{detalle}</small></article>}
function TarjetaLateral({titulo,elementos}:{titulo:string;elementos:Array<{titulo:string;texto:string}>}){return <section className={estilos.tarjeta}><header><h2>{titulo}</h2></header><div className={estilos.listaLateral}>{elementos.map((item,index)=><article key={`${titulo}-${index}`}><strong>{item.titulo}</strong><span>{item.texto}</span></article>)}</div></section>}
