"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { adaptarSesion } from "@/features/monitores/api/adaptadoresMonitores";
import type { SesionApi } from "@/features/monitores/api/contratosMonitores";
import { servicioMonitores } from "@/features/monitores/api/servicioMonitores";
import { usarRecursoApi } from "@/features/monitores/ganchos/usarRecursoApi";
import { usarPaginacion } from "@/features/monitores/ganchos/usarPaginacion";
import { Paginacion } from "./Paginacion";
import { AvisoTemporal } from "./AvisoTemporal";
import estilos from "./SistemaVisualMonitores.module.css";

export function RevisionHorasExtra() {
  const recurso = usarRecursoApi(servicioMonitores.listarSesiones, [] as SesionApi[]);
  const recursoMonitores = usarRecursoApi(servicioMonitores.listarMonitores, []);
  const [monitor, setMonitor] = useState(""); const [fecha, setFecha] = useState(""); const [minimo, setMinimo] = useState(""); const [decisiones, setDecisiones] = useState<Record<string, "APROBAR" | "RECHAZAR">>({}); const [notas, setNotas] = useState<Record<string, string>>({}); const [penalizar, setPenalizar] = useState<Record<string, boolean>>({}); const [aviso, setAviso] = useState(""); const [procesando, setProcesando] = useState("");
  const [asignacion, setAsignacion] = useState({ monitorId: "", fecha: new Date().toISOString().slice(0, 10), horas: "", motivo: "" });
  const [asignando, setAsignando] = useState(false);
  const pendientes = useMemo(() => recurso.datos.filter((item) => item.overtime_status === "pending"), [recurso.datos]);
  const filtradas = useMemo(() => pendientes.filter((item) => (!monitor || item.monitor_name.toLocaleLowerCase("es").includes(monitor.toLocaleLowerCase("es"))) && (!fecha || item.work_day === fecha) && (!minimo || item.overtime_minutes / 60 >= Number(minimo))), [pendientes, monitor, fecha, minimo]);
  const paginacion = usarPaginacion(filtradas, 8);
  async function guardar(sesion: SesionApi) { const decision = decisiones[sesion.id] ?? "APROBAR"; const nota = notas[sesion.id]?.trim() ?? ""; if (decision === "RECHAZAR" && !nota) { setAviso("Si eliges rechazar, debes escribir la anotación obligatoriamente."); return; } setProcesando(sesion.id); setAviso(""); try { const actualizada = await servicioMonitores.revisarHorasExtra(sesion.id, { decision: decision === "APROBAR" ? "approve" : "reject", note: nota, penalize_on_reject: penalizar[sesion.id] ?? false }); recurso.setDatos((actual) => actual.map((item) => item.id === sesion.id ? actualizada : item)); setAviso(`${decision === "APROBAR" ? "Se aprobaron" : "Se rechazaron"} ${(sesion.overtime_minutes / 60).toFixed(1)} h.`); } catch (problema) { setAviso(problema instanceof Error ? problema.message : "No fue posible guardar la decisión."); } finally { setProcesando(""); } }
  async function asignarHorasExtra(evento: FormEvent<HTMLFormElement>) {
    evento.preventDefault();
    const horas = Number(asignacion.horas);
    if (!asignacion.monitorId || !asignacion.fecha || !asignacion.motivo.trim() || !Number.isFinite(horas) || horas < 0.01 || horas > 24) {
      setAviso("Selecciona un monitor, una fecha, entre 0.01 y 24 horas y el motivo de la asignación.");
      return;
    }
    setAsignando(true); setAviso("");
    try {
      await servicioMonitores.crearAnotacion({ monitor: asignacion.monitorId, session: null, annotation_type: "virtual_hours", action: "add", delta_minutes: Math.round(horas * 60), occurred_on: asignacion.fecha, description: `Horas extra asignadas manualmente: ${asignacion.motivo.trim()}` });
      setAsignacion({ monitorId: "", fecha: new Date().toISOString().slice(0, 10), horas: "", motivo: "" });
      setAviso(`Se asignaron ${horas.toFixed(2)} horas extra manuales. El ajuste ya está disponible en el resumen del monitor.`);
    } catch (problema) { setAviso(problema instanceof Error ? problema.message : "No fue posible asignar las horas extra."); } finally { setAsignando(false); }
  }
  function limpiar() { setMonitor(""); setFecha(""); setMinimo(""); paginacion.reiniciar(); }
  return <div className={estilos.revisionHorasExtra}>
    <section className={`page-heading ${estilos.encabezado}`}><div><span className={estilos.etiqueta}>Control de novedades</span><h1>Horas extra por aprobar</h1><p>Revise cada registro y tome una decisión sobre el tiempo fuera del turno.</p></div><span className={`${estilos.insignia} ${estilos.advertencia}`}>{filtradas.length} sesiones visibles</span></section>
    {recurso.error && <div className={`${estilos.aviso} ${estilos.avisoError}`}>{recurso.error}</div>}{aviso && <AvisoTemporal mensaje={aviso} tipo={aviso.startsWith("Se ") ? "exito" : "error"} alCerrar={() => setAviso("")} />}
    <section className={estilos.tarjeta}><header><div><h2>Asignar horas extra</h2><p>Registre horas adicionales directamente, sin depender de una marcación pendiente de revisión.</p></div></header><form className={estilos.barraHerramientas} onSubmit={asignarHorasExtra}><label className={estilos.campo}><span>Monitor</span><select value={asignacion.monitorId} onChange={(e) => setAsignacion({ ...asignacion, monitorId: e.target.value })} required><option value="">Seleccione un monitor</option>{recursoMonitores.datos.filter((item) => item.is_active && item.semester_is_active === true).map((item) => <option key={item.id} value={item.id}>{item.full_name} · {item.codigo_estudiante}</option>)}</select></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={asignacion.fecha} onChange={(e) => setAsignacion({ ...asignacion, fecha: e.target.value })} required /></label><label className={estilos.campo}><span>Horas extra (h)</span><input type="number" min="0.01" max="24" step="0.01" value={asignacion.horas} onChange={(e) => setAsignacion({ ...asignacion, horas: e.target.value })} required /></label><label className={estilos.campoAncho}><span>Motivo</span><input value={asignacion.motivo} onChange={(e) => setAsignacion({ ...asignacion, motivo: e.target.value })} maxLength={1000} placeholder="Ej. Apoyo adicional en laboratorio" required /></label><div className={estilos.accionesFormulario}><button className="button-primary" disabled={asignando || recursoMonitores.cargando}>{asignando ? "Asignando…" : "Asignar horas"}</button></div></form></section>
    <section className={estilos.tarjeta}><div className={estilos.barraHerramientas}><label className={estilos.campoAncho}><span>Monitor</span><input value={monitor} onChange={(e) => { setMonitor(e.target.value); paginacion.reiniciar(); }} placeholder="Filtrar monitor" /></label><label className={estilos.campo}><span>Fecha</span><input type="date" value={fecha} onChange={(e) => { setFecha(e.target.value); paginacion.reiniciar(); }} /></label><label className={estilos.campo}><span>Horas extra por aprobar (h)</span><input type="number" min="0" step="0.25" value={minimo} onChange={(e) => { setMinimo(e.target.value); paginacion.reiniciar(); }} placeholder="Mínimo" /></label><div className={estilos.accionesFormulario}><button type="button" className={estilos.botonSecundario} onClick={limpiar}>Limpiar</button></div></div>
      <div className={estilos.tablaContenedor}><table className={`${estilos.tabla} ${estilos.tablaRevisionExtra}`}><thead><tr><th>Monitor</th><th>Fecha</th><th>Horas extra por aprobar (h)</th><th>Registro</th><th>Acción</th></tr></thead><tbody>{paginacion.visibles.map((sesion) => { const adaptada = adaptarSesion(sesion); const decision = decisiones[sesion.id] ?? "APROBAR"; const rechaza = decision === "RECHAZAR"; return <tr key={sesion.id}><td><strong>{sesion.monitor_name}</strong></td><td>{adaptada.fecha}</td><td><strong>{adaptada.horasExtra.toFixed(1)} h</strong></td><td><Link className={estilos.botonSecundario} href={`/gestion-monitores/registros/${sesion.monitor}?dia=${sesion.work_day}`}>Ver registro</Link></td><td><section className={estilos.panelDecision}><div><span className={estilos.etiqueta}>Decisión</span><label className={estilos.campo}><select value={decision} onChange={(e) => setDecisiones({ ...decisiones, [sesion.id]: e.target.value as "APROBAR" | "RECHAZAR" })}><option value="APROBAR">Aprobar</option><option value="RECHAZAR">Rechazar</option></select></label></div><div className={estilos.anotacionDecision}><label className={estilos.campo}><span>Anotación {rechaza ? "obligatoria" : "opcional"}</span><input value={notas[sesion.id] ?? ""} onChange={(e) => setNotas({ ...notas, [sesion.id]: e.target.value })} placeholder="Anotación opcional" required={rechaza} /></label><p>Si eliges rechazar, debes escribir la anotación obligatoriamente.</p></div><label className={estilos.verificacion}><input type="checkbox" checked={penalizar[sesion.id] ?? false} disabled={!rechaza} onChange={(e) => setPenalizar({ ...penalizar, [sesion.id]: e.target.checked })} /><span><strong>Penalizar al monitor al rechazar</strong><small>Si está marcado, no se suman las horas extra y se descuenta el mismo valor por medio de una anotación. Si no, solo se rechazan.</small></span></label><div className={estilos.accionesFormulario}><button className="button-primary" type="button" disabled={procesando === sesion.id} onClick={() => void guardar(sesion)}>{procesando === sesion.id ? "Guardando…" : "Guardar"}</button></div></section></td></tr>; })}{!recurso.cargando && !filtradas.length && <tr><td colSpan={5} className={estilos.vacio}>No hay horas extra pendientes con los filtros actuales.</td></tr>}</tbody></table></div><Paginacion {...paginacion} total={filtradas.length} />
    </section>
  </div>;
}
