-- El catálogo solo conserva permisos que respaldan una capacidad existente.
-- Las relaciones RolPermiso se eliminan en cascada por la clave foránea.
DELETE FROM "Permiso"
WHERE "codigo" IN (
  'DASHBOARD_CREAR', 'DASHBOARD_ACTUALIZAR', 'DASHBOARD_ELIMINAR', 'DASHBOARD_APROBAR', 'DASHBOARD_EXPORTAR',
  'AULAS_APROBAR', 'AULAS_EXPORTAR',
  'DISPONIBILIDAD_CREAR', 'DISPONIBILIDAD_ACTUALIZAR', 'DISPONIBILIDAD_ELIMINAR', 'DISPONIBILIDAD_APROBAR', 'DISPONIBILIDAD_EXPORTAR',
  'PRACTICAS_LIBRES_ELIMINAR', 'PRACTICAS_LIBRES_APROBAR', 'PRACTICAS_LIBRES_EXPORTAR',
  'PRESTAMOS_DOCENTES_ELIMINAR', 'PRESTAMOS_DOCENTES_EXPORTAR',
  'AUDIOVISUALES_EXPORTAR',
  'SOFTWARE_APROBAR', 'SOFTWARE_EXPORTAR',
  'OBSERVACIONES_APROBAR', 'OBSERVACIONES_EXPORTAR',
  'LIMPIEZA_APROBAR', 'LIMPIEZA_EXPORTAR',
  'TAREAS_EXPORTAR',
  'MULTAS_ELIMINAR', 'MULTAS_APROBAR', 'MULTAS_EXPORTAR',
  'CREDENCIALES_APROBAR', 'CREDENCIALES_EXPORTAR',
  'REPORTES_CREAR', 'REPORTES_ACTUALIZAR', 'REPORTES_ELIMINAR', 'REPORTES_APROBAR', 'REPORTES_EXPORTAR',
  'ADMINISTRACION_APROBAR', 'ADMINISTRACION_EXPORTAR'
);
