import type { FormEvent } from "react";
import type { FormularioCuentaMonitor } from "./tipos";
import estilos from "../SistemaVisualMonitores.module.css";

type FormularioCuentaProps = { formulario: FormularioCuentaMonitor; editando: boolean; onCambio: (datos: FormularioCuentaMonitor) => void; onCancelar: () => void; onSubmit: (evento: FormEvent<HTMLFormElement>) => void };

export function FormularioCuenta({ formulario, editando, onCambio, onCancelar, onSubmit }: FormularioCuentaProps) {
  return <section className={`${estilos.tarjeta} ${estilos.formularioFijo}`}><header><div><h2>{editando ? "Editar monitor" : "Registrar monitor"}</h2><p>La cuenta se crea sin contraseña y recibe un enlace para activar su acceso.</p></div></header><form className={estilos.formulario} onSubmit={onSubmit}><Campo etiqueta="Nombre completo"><input value={formulario.nombre} onChange={(e) => onCambio({ ...formulario, nombre: e.target.value })} required /></Campo><Campo etiqueta="Código estudiantil"><input value={formulario.codigo} onChange={(e) => onCambio({ ...formulario, codigo: e.target.value })} required /></Campo><Campo etiqueta="Número de documento"><input value={formulario.documento} onChange={(e) => onCambio({ ...formulario, documento: e.target.value })} required /></Campo><Campo etiqueta="Correo institucional"><input type="email" value={formulario.correo} onChange={(e) => onCambio({ ...formulario, correo: e.target.value })} required /></Campo><Campo etiqueta="Proyecto curricular"><select value={formulario.proyecto} onChange={(e) => onCambio({ ...formulario, proyecto: e.target.value })} required><option value="">Seleccione un proyecto curricular</option><option>Ingeniería de Sistemas</option><option>Tecnología en Software</option><option>Ingeniería Eléctrica</option><option>Física</option></select></Campo><Campo etiqueta="Teléfono"><input value={formulario.telefono} onChange={(e) => onCambio({ ...formulario, telefono: e.target.value })} required /></Campo><Campo etiqueta="Dependencia"><select value={formulario.dependencia} onChange={(e) => onCambio({ ...formulario, dependencia: e.target.value })}><option>Monitores Física</option><option>Monitores Aulas de Software</option><option>Monitores Laboratorios</option></select></Campo><label className={estilos.verificacion}><input type="checkbox" checked={formulario.repite} onChange={(e) => onCambio({ ...formulario, repite: e.target.checked })} /><span><strong>Confirmo que este monitor ya hizo monitorías y repetirá en el semestre actual</strong></span></label><div className={estilos.accionesFormulario}>{editando && <button type="button" className={estilos.botonSecundario} onClick={onCancelar}>Cancelar</button>}<button className="button-primary">{editando ? "Guardar cambios" : "+ Crear y enviar activación"}</button></div></form></section>;
}

function Campo({ etiqueta, children }: { etiqueta: string; children: React.ReactNode }) { return <label className={estilos.campo}><span>{etiqueta}</span>{children}</label>; }
