export const IS_PUBLIC_KEY = 'auth:is-public';
export const REQUIRE_AUTH_KEY = 'auth:required';
export const REQUIRED_MODULE_KEY = 'auth:required-module';
export const REQUIRED_PERMISSIONS_KEY = 'auth:required-permissions';

export const MODULOS = {
  AULAS: 'AULAS',
  HORARIOS: 'HORARIOS',
  ASISTENCIA_DOCENTE: 'ASISTENCIA_DOCENTE',
  DISPONIBILIDAD_AULAS: 'DISPONIBILIDAD_AULAS',
  PRACTICAS_LIBRES: 'PRACTICAS_LIBRES',
  PRESTAMOS_DOCENTES: 'PRESTAMOS_DOCENTES',
  OBSERVACIONES: 'OBSERVACIONES',
} as const;
