export const IS_PUBLIC_KEY = 'auth:is-public';
export const REQUIRE_AUTH_KEY = 'auth:required';
export const REQUIRED_MODULE_KEY = 'auth:required-module';
export const REQUIRED_PERMISSIONS_KEY = 'auth:required-permissions';
export const REQUIRE_ADMINISTRATOR_KEY = 'auth:require-administrator';

export const MODULOS = {
  AULAS: 'AULAS',
  HORARIOS: 'HORARIOS',
  ASISTENCIA_DOCENTE: 'ASISTENCIA_DOCENTE',
  DISPONIBILIDAD_AULAS: 'DISPONIBILIDAD',
  PRACTICAS_LIBRES: 'PRACTICAS_LIBRES',
  PRESTAMOS_DOCENTES: 'PRESTAMOS_DOCENTES',
  AUDIOVISUALES: 'AUDIOVISUALES',
  SOFTWARE: 'SOFTWARE',
  OBSERVACIONES: 'OBSERVACIONES',
  LIMPIEZA: 'LIMPIEZA',
  CREDENCIALES: 'CREDENCIALES',
  TAREAS: 'TAREAS',
  PANEL_OPERATIVO: 'DASHBOARD',
  MULTAS: 'MULTAS',
  REPORTES: 'REPORTES',
  ESTUDIANTES: 'ESTUDIANTES',
  DOCENTES: 'DOCENTES',
} as const;

/**
 * Catálogos de solo lectura que un módulo operativo necesita para completar
 * su propio flujo. No concede permisos de creación, actualización o borrado.
 */
export const MODULOS_CON_LECTURA_AUXILIAR: Record<string, readonly string[]> = {
  AULAS: [MODULOS.HORARIOS, MODULOS.LIMPIEZA, MODULOS.TAREAS],
  SOFTWARE: [MODULOS.PRACTICAS_LIBRES, MODULOS.PRESTAMOS_DOCENTES],
  DISPONIBILIDAD: [MODULOS.PRACTICAS_LIBRES, MODULOS.PRESTAMOS_DOCENTES],
  DOCENTES: [MODULOS.PRESTAMOS_DOCENTES, MODULOS.AUDIOVISUALES],
  OBSERVACIONES: [MODULOS.LIMPIEZA],
};
